#ifndef INCLUDED_CYFITTER_H
#define INCLUDED_CYFITTER_H
#include <cydevice_trm.h>

/* ADC_Bypass */
#define ADC_Bypass__0__DM__MASK 0xE00000u
#define ADC_Bypass__0__DM__SHIFT 21
#define ADC_Bypass__0__DR CYREG_PRT1_DR
#define ADC_Bypass__0__HSIOM CYREG_HSIOM_PORT_SEL1
#define ADC_Bypass__0__HSIOM_MASK 0xF0000000u
#define ADC_Bypass__0__HSIOM_SHIFT 28u
#define ADC_Bypass__0__INTCFG CYREG_PRT1_INTCFG
#define ADC_Bypass__0__INTSTAT CYREG_PRT1_INTSTAT
#define ADC_Bypass__0__MASK 0x80u
#define ADC_Bypass__0__PA__CFG0 CYREG_UDB_PA1_CFG0
#define ADC_Bypass__0__PA__CFG1 CYREG_UDB_PA1_CFG1
#define ADC_Bypass__0__PA__CFG10 CYREG_UDB_PA1_CFG10
#define ADC_Bypass__0__PA__CFG11 CYREG_UDB_PA1_CFG11
#define ADC_Bypass__0__PA__CFG12 CYREG_UDB_PA1_CFG12
#define ADC_Bypass__0__PA__CFG13 CYREG_UDB_PA1_CFG13
#define ADC_Bypass__0__PA__CFG14 CYREG_UDB_PA1_CFG14
#define ADC_Bypass__0__PA__CFG2 CYREG_UDB_PA1_CFG2
#define ADC_Bypass__0__PA__CFG3 CYREG_UDB_PA1_CFG3
#define ADC_Bypass__0__PA__CFG4 CYREG_UDB_PA1_CFG4
#define ADC_Bypass__0__PA__CFG5 CYREG_UDB_PA1_CFG5
#define ADC_Bypass__0__PA__CFG6 CYREG_UDB_PA1_CFG6
#define ADC_Bypass__0__PA__CFG7 CYREG_UDB_PA1_CFG7
#define ADC_Bypass__0__PA__CFG8 CYREG_UDB_PA1_CFG8
#define ADC_Bypass__0__PA__CFG9 CYREG_UDB_PA1_CFG9
#define ADC_Bypass__0__PC CYREG_PRT1_PC
#define ADC_Bypass__0__PC2 CYREG_PRT1_PC2
#define ADC_Bypass__0__PORT 1u
#define ADC_Bypass__0__PS CYREG_PRT1_PS
#define ADC_Bypass__0__SHIFT 7
#define ADC_Bypass__DR CYREG_PRT1_DR
#define ADC_Bypass__INTCFG CYREG_PRT1_INTCFG
#define ADC_Bypass__INTSTAT CYREG_PRT1_INTSTAT
#define ADC_Bypass__MASK 0x80u
#define ADC_Bypass__PA__CFG0 CYREG_UDB_PA1_CFG0
#define ADC_Bypass__PA__CFG1 CYREG_UDB_PA1_CFG1
#define ADC_Bypass__PA__CFG10 CYREG_UDB_PA1_CFG10
#define ADC_Bypass__PA__CFG11 CYREG_UDB_PA1_CFG11
#define ADC_Bypass__PA__CFG12 CYREG_UDB_PA1_CFG12
#define ADC_Bypass__PA__CFG13 CYREG_UDB_PA1_CFG13
#define ADC_Bypass__PA__CFG14 CYREG_UDB_PA1_CFG14
#define ADC_Bypass__PA__CFG2 CYREG_UDB_PA1_CFG2
#define ADC_Bypass__PA__CFG3 CYREG_UDB_PA1_CFG3
#define ADC_Bypass__PA__CFG4 CYREG_UDB_PA1_CFG4
#define ADC_Bypass__PA__CFG5 CYREG_UDB_PA1_CFG5
#define ADC_Bypass__PA__CFG6 CYREG_UDB_PA1_CFG6
#define ADC_Bypass__PA__CFG7 CYREG_UDB_PA1_CFG7
#define ADC_Bypass__PA__CFG8 CYREG_UDB_PA1_CFG8
#define ADC_Bypass__PA__CFG9 CYREG_UDB_PA1_CFG9
#define ADC_Bypass__PC CYREG_PRT1_PC
#define ADC_Bypass__PC2 CYREG_PRT1_PC2
#define ADC_Bypass__PORT 1u
#define ADC_Bypass__PS CYREG_PRT1_PS
#define ADC_Bypass__SHIFT 7

/* ADC_cy_psoc4_sar */
#define ADC_cy_psoc4_sar__SAR_CTRL CYREG_SAR_CTRL
#define ADC_cy_psoc4_sar__SAR_INTR CYREG_SAR_INTR
#define ADC_cy_psoc4_sar__SAR_INTR_CAUSE CYREG_SAR_INTR_CAUSE
#define ADC_cy_psoc4_sar__SAR_INTR_MASK CYREG_SAR_INTR_MASK
#define ADC_cy_psoc4_sar__SAR_INTR_MASKED CYREG_SAR_INTR_MASKED
#define ADC_cy_psoc4_sar__SAR_INTR_SET CYREG_SAR_INTR_SET
#define ADC_cy_psoc4_sar__SAR_NUMBER 0u
#define ADC_cy_psoc4_sar__SAR_RANGE_COND CYREG_SAR_RANGE_COND
#define ADC_cy_psoc4_sar__SAR_RANGE_INTR_MASK CYREG_SAR_RANGE_INTR_MASK
#define ADC_cy_psoc4_sar__SAR_RANGE_INTR_MASKED CYREG_SAR_RANGE_INTR_MASKED
#define ADC_cy_psoc4_sar__SAR_RANGE_INTR_SET CYREG_SAR_RANGE_INTR_SET
#define ADC_cy_psoc4_sar__SAR_RANGE_THRES CYREG_SAR_RANGE_THRES
#define ADC_cy_psoc4_sar__SAR_SAMPLE_CTRL CYREG_SAR_SAMPLE_CTRL
#define ADC_cy_psoc4_sar__SAR_SAMPLE_TIME01 CYREG_SAR_SAMPLE_TIME01
#define ADC_cy_psoc4_sar__SAR_SAMPLE_TIME23 CYREG_SAR_SAMPLE_TIME23
#define ADC_cy_psoc4_sar__SAR_SATURATE_INTR_MASK CYREG_SAR_SATURATE_INTR_MASK
#define ADC_cy_psoc4_sar__SAR_SATURATE_INTR_MASKED CYREG_SAR_SATURATE_INTR_MASKED
#define ADC_cy_psoc4_sar__SAR_SATURATE_INTR_SET CYREG_SAR_SATURATE_INTR_SET

/* ADC_cy_psoc4_sarmux_8 */
#define ADC_cy_psoc4_sarmux_8__CH_0_PIN 4
#define ADC_cy_psoc4_sarmux_8__CH_0_PORT 0
#define ADC_cy_psoc4_sarmux_8__CH_1_PIN 3
#define ADC_cy_psoc4_sarmux_8__CH_1_PORT 0
#define ADC_cy_psoc4_sarmux_8__CH_2_PIN 2
#define ADC_cy_psoc4_sarmux_8__CH_2_PORT 1
#define ADC_cy_psoc4_sarmux_8__CH_3_PIN 2
#define ADC_cy_psoc4_sarmux_8__CH_3_PORT 0
#define ADC_cy_psoc4_sarmux_8__CH_4_PIN 0
#define ADC_cy_psoc4_sarmux_8__CH_4_PORT 7
#define ADC_cy_psoc4_sarmux_8__CH_5_PIN 5
#define ADC_cy_psoc4_sarmux_8__CH_5_PORT 0
#define ADC_cy_psoc4_sarmux_8__SAR_CHAN_CONFIG00 CYREG_SAR_CHAN_CONFIG00
#define ADC_cy_psoc4_sarmux_8__SAR_CHAN_CONFIG01 CYREG_SAR_CHAN_CONFIG01
#define ADC_cy_psoc4_sarmux_8__SAR_CHAN_CONFIG02 CYREG_SAR_CHAN_CONFIG02
#define ADC_cy_psoc4_sarmux_8__SAR_CHAN_CONFIG03 CYREG_SAR_CHAN_CONFIG03
#define ADC_cy_psoc4_sarmux_8__SAR_CHAN_CONFIG04 CYREG_SAR_CHAN_CONFIG04
#define ADC_cy_psoc4_sarmux_8__SAR_CHAN_CONFIG05 CYREG_SAR_CHAN_CONFIG05
#define ADC_cy_psoc4_sarmux_8__SAR_CHAN_CONFIG06 CYREG_SAR_CHAN_CONFIG06
#define ADC_cy_psoc4_sarmux_8__SAR_CHAN_CONFIG07 CYREG_SAR_CHAN_CONFIG07
#define ADC_cy_psoc4_sarmux_8__SAR_CHAN_EN CYREG_SAR_CHAN_EN
#define ADC_cy_psoc4_sarmux_8__SAR_CHAN_RESULT_VALID CYREG_SAR_CHAN_RESULT_VALID
#define ADC_cy_psoc4_sarmux_8__SAR_CHAN_RESULT00 CYREG_SAR_CHAN_RESULT00
#define ADC_cy_psoc4_sarmux_8__SAR_CHAN_RESULT01 CYREG_SAR_CHAN_RESULT01
#define ADC_cy_psoc4_sarmux_8__SAR_CHAN_RESULT02 CYREG_SAR_CHAN_RESULT02
#define ADC_cy_psoc4_sarmux_8__SAR_CHAN_RESULT03 CYREG_SAR_CHAN_RESULT03
#define ADC_cy_psoc4_sarmux_8__SAR_CHAN_RESULT04 CYREG_SAR_CHAN_RESULT04
#define ADC_cy_psoc4_sarmux_8__SAR_CHAN_RESULT05 CYREG_SAR_CHAN_RESULT05
#define ADC_cy_psoc4_sarmux_8__SAR_CHAN_RESULT06 CYREG_SAR_CHAN_RESULT06
#define ADC_cy_psoc4_sarmux_8__SAR_CHAN_RESULT07 CYREG_SAR_CHAN_RESULT07
#define ADC_cy_psoc4_sarmux_8__SAR_CHAN_WORK_VALID CYREG_SAR_CHAN_WORK_VALID
#define ADC_cy_psoc4_sarmux_8__SAR_CHAN_WORK00 CYREG_SAR_CHAN_WORK00
#define ADC_cy_psoc4_sarmux_8__SAR_CHAN_WORK01 CYREG_SAR_CHAN_WORK01
#define ADC_cy_psoc4_sarmux_8__SAR_CHAN_WORK02 CYREG_SAR_CHAN_WORK02
#define ADC_cy_psoc4_sarmux_8__SAR_CHAN_WORK03 CYREG_SAR_CHAN_WORK03
#define ADC_cy_psoc4_sarmux_8__SAR_CHAN_WORK04 CYREG_SAR_CHAN_WORK04
#define ADC_cy_psoc4_sarmux_8__SAR_CHAN_WORK05 CYREG_SAR_CHAN_WORK05
#define ADC_cy_psoc4_sarmux_8__SAR_CHAN_WORK06 CYREG_SAR_CHAN_WORK06
#define ADC_cy_psoc4_sarmux_8__SAR_CHAN_WORK07 CYREG_SAR_CHAN_WORK07
#define ADC_cy_psoc4_sarmux_8__SAR_INJ_CHAN_CONFIG CYREG_SAR_INJ_CHAN_CONFIG
#define ADC_cy_psoc4_sarmux_8__SAR_INJ_RESULT CYREG_SAR_INJ_RESULT
#define ADC_cy_psoc4_sarmux_8__SAR_START_CTRL CYREG_SAR_START_CTRL

/* ADC_intClock */
#define ADC_intClock__DIVIDER_MASK 0x0000FFFFu
#define ADC_intClock__ENABLE CYREG_CLK_DIVIDER_A00
#define ADC_intClock__ENABLE_MASK 0x80000000u
#define ADC_intClock__MASK 0x80000000u
#define ADC_intClock__REGISTER CYREG_CLK_DIVIDER_A00

/* ADC_IRQ */
#define ADC_IRQ__INTC_CLR_EN_REG CYREG_CM0_ICER
#define ADC_IRQ__INTC_CLR_PD_REG CYREG_CM0_ICPR
#define ADC_IRQ__INTC_MASK 0x4000u
#define ADC_IRQ__INTC_NUMBER 14u
#define ADC_IRQ__INTC_PRIOR_MASK 0xC00000u
#define ADC_IRQ__INTC_PRIOR_NUM 3u
#define ADC_IRQ__INTC_PRIOR_REG CYREG_CM0_IPR3
#define ADC_IRQ__INTC_SET_EN_REG CYREG_CM0_ISER
#define ADC_IRQ__INTC_SET_PD_REG CYREG_CM0_ISPR

/* UART_Clock */
#define UART_Clock__DIVIDER_MASK 0x0000FFFFu
#define UART_Clock__ENABLE CYREG_CLK_DIVIDER_FRAC_A00
#define UART_Clock__ENABLE_MASK 0x80000000u
#define UART_Clock__FRAC_MASK 0x001F0000u
#define UART_Clock__MASK 0x80000000u
#define UART_Clock__REGISTER CYREG_CLK_DIVIDER_FRAC_A00

/* UART_ISR */
#define UART_ISR__INTC_CLR_EN_REG CYREG_CM0_ICER
#define UART_ISR__INTC_CLR_PD_REG CYREG_CM0_ICPR
#define UART_ISR__INTC_MASK 0x400u
#define UART_ISR__INTC_NUMBER 10u
#define UART_ISR__INTC_PRIOR_MASK 0xC00000u
#define UART_ISR__INTC_PRIOR_NUM 3u
#define UART_ISR__INTC_PRIOR_REG CYREG_CM0_IPR2
#define UART_ISR__INTC_SET_EN_REG CYREG_CM0_ISER
#define UART_ISR__INTC_SET_PD_REG CYREG_CM0_ISPR

/* UART_rx */
#define UART_rx__0__DM__MASK 0x07u
#define UART_rx__0__DM__SHIFT 0
#define UART_rx__0__DR CYREG_PRT4_DR
#define UART_rx__0__HSIOM CYREG_HSIOM_PORT_SEL4
#define UART_rx__0__HSIOM_MASK 0x0000000Fu
#define UART_rx__0__HSIOM_SHIFT 0u
#define UART_rx__0__INTCFG CYREG_PRT4_INTCFG
#define UART_rx__0__INTSTAT CYREG_PRT4_INTSTAT
#define UART_rx__0__MASK 0x01u
#define UART_rx__0__PC CYREG_PRT4_PC
#define UART_rx__0__PC2 CYREG_PRT4_PC2
#define UART_rx__0__PORT 4u
#define UART_rx__0__PS CYREG_PRT4_PS
#define UART_rx__0__SHIFT 0
#define UART_rx__DR CYREG_PRT4_DR
#define UART_rx__INTCFG CYREG_PRT4_INTCFG
#define UART_rx__INTSTAT CYREG_PRT4_INTSTAT
#define UART_rx__MASK 0x01u
#define UART_rx__PC CYREG_PRT4_PC
#define UART_rx__PC2 CYREG_PRT4_PC2
#define UART_rx__PORT 4u
#define UART_rx__PS CYREG_PRT4_PS
#define UART_rx__SHIFT 0

/* UART_SCB */
#define UART_SCB__BIST_CONTROL CYREG_SCB0_BIST_CONTROL
#define UART_SCB__BIST_DATA CYREG_SCB0_BIST_DATA
#define UART_SCB__CTRL CYREG_SCB0_CTRL
#define UART_SCB__EZ_DATA00 CYREG_SCB0_EZ_DATA00
#define UART_SCB__EZ_DATA01 CYREG_SCB0_EZ_DATA01
#define UART_SCB__EZ_DATA02 CYREG_SCB0_EZ_DATA02
#define UART_SCB__EZ_DATA03 CYREG_SCB0_EZ_DATA03
#define UART_SCB__EZ_DATA04 CYREG_SCB0_EZ_DATA04
#define UART_SCB__EZ_DATA05 CYREG_SCB0_EZ_DATA05
#define UART_SCB__EZ_DATA06 CYREG_SCB0_EZ_DATA06
#define UART_SCB__EZ_DATA07 CYREG_SCB0_EZ_DATA07
#define UART_SCB__EZ_DATA08 CYREG_SCB0_EZ_DATA08
#define UART_SCB__EZ_DATA09 CYREG_SCB0_EZ_DATA09
#define UART_SCB__EZ_DATA10 CYREG_SCB0_EZ_DATA10
#define UART_SCB__EZ_DATA11 CYREG_SCB0_EZ_DATA11
#define UART_SCB__EZ_DATA12 CYREG_SCB0_EZ_DATA12
#define UART_SCB__EZ_DATA13 CYREG_SCB0_EZ_DATA13
#define UART_SCB__EZ_DATA14 CYREG_SCB0_EZ_DATA14
#define UART_SCB__EZ_DATA15 CYREG_SCB0_EZ_DATA15
#define UART_SCB__EZ_DATA16 CYREG_SCB0_EZ_DATA16
#define UART_SCB__EZ_DATA17 CYREG_SCB0_EZ_DATA17
#define UART_SCB__EZ_DATA18 CYREG_SCB0_EZ_DATA18
#define UART_SCB__EZ_DATA19 CYREG_SCB0_EZ_DATA19
#define UART_SCB__EZ_DATA20 CYREG_SCB0_EZ_DATA20
#define UART_SCB__EZ_DATA21 CYREG_SCB0_EZ_DATA21
#define UART_SCB__EZ_DATA22 CYREG_SCB0_EZ_DATA22
#define UART_SCB__EZ_DATA23 CYREG_SCB0_EZ_DATA23
#define UART_SCB__EZ_DATA24 CYREG_SCB0_EZ_DATA24
#define UART_SCB__EZ_DATA25 CYREG_SCB0_EZ_DATA25
#define UART_SCB__EZ_DATA26 CYREG_SCB0_EZ_DATA26
#define UART_SCB__EZ_DATA27 CYREG_SCB0_EZ_DATA27
#define UART_SCB__EZ_DATA28 CYREG_SCB0_EZ_DATA28
#define UART_SCB__EZ_DATA29 CYREG_SCB0_EZ_DATA29
#define UART_SCB__EZ_DATA30 CYREG_SCB0_EZ_DATA30
#define UART_SCB__EZ_DATA31 CYREG_SCB0_EZ_DATA31
#define UART_SCB__I2C_CFG CYREG_SCB0_I2C_CFG
#define UART_SCB__I2C_CTRL CYREG_SCB0_I2C_CTRL
#define UART_SCB__I2C_M_CMD CYREG_SCB0_I2C_M_CMD
#define UART_SCB__I2C_S_CMD CYREG_SCB0_I2C_S_CMD
#define UART_SCB__I2C_STATUS CYREG_SCB0_I2C_STATUS
#define UART_SCB__INTR_CAUSE CYREG_SCB0_INTR_CAUSE
#define UART_SCB__INTR_I2C_EC CYREG_SCB0_INTR_I2C_EC
#define UART_SCB__INTR_I2C_EC_MASK CYREG_SCB0_INTR_I2C_EC_MASK
#define UART_SCB__INTR_I2C_EC_MASKED CYREG_SCB0_INTR_I2C_EC_MASKED
#define UART_SCB__INTR_M CYREG_SCB0_INTR_M
#define UART_SCB__INTR_M_MASK CYREG_SCB0_INTR_M_MASK
#define UART_SCB__INTR_M_MASKED CYREG_SCB0_INTR_M_MASKED
#define UART_SCB__INTR_M_SET CYREG_SCB0_INTR_M_SET
#define UART_SCB__INTR_RX CYREG_SCB0_INTR_RX
#define UART_SCB__INTR_RX_MASK CYREG_SCB0_INTR_RX_MASK
#define UART_SCB__INTR_RX_MASKED CYREG_SCB0_INTR_RX_MASKED
#define UART_SCB__INTR_RX_SET CYREG_SCB0_INTR_RX_SET
#define UART_SCB__INTR_S CYREG_SCB0_INTR_S
#define UART_SCB__INTR_S_MASK CYREG_SCB0_INTR_S_MASK
#define UART_SCB__INTR_S_MASKED CYREG_SCB0_INTR_S_MASKED
#define UART_SCB__INTR_S_SET CYREG_SCB0_INTR_S_SET
#define UART_SCB__INTR_SPI_EC CYREG_SCB0_INTR_SPI_EC
#define UART_SCB__INTR_SPI_EC_MASK CYREG_SCB0_INTR_SPI_EC_MASK
#define UART_SCB__INTR_SPI_EC_MASKED CYREG_SCB0_INTR_SPI_EC_MASKED
#define UART_SCB__INTR_TX CYREG_SCB0_INTR_TX
#define UART_SCB__INTR_TX_MASK CYREG_SCB0_INTR_TX_MASK
#define UART_SCB__INTR_TX_MASKED CYREG_SCB0_INTR_TX_MASKED
#define UART_SCB__INTR_TX_SET CYREG_SCB0_INTR_TX_SET
#define UART_SCB__RX_CTRL CYREG_SCB0_RX_CTRL
#define UART_SCB__RX_FIFO_CTRL CYREG_SCB0_RX_FIFO_CTRL
#define UART_SCB__RX_FIFO_RD CYREG_SCB0_RX_FIFO_RD
#define UART_SCB__RX_FIFO_RD_SILENT CYREG_SCB0_RX_FIFO_RD_SILENT
#define UART_SCB__RX_FIFO_STATUS CYREG_SCB0_RX_FIFO_STATUS
#define UART_SCB__RX_MATCH CYREG_SCB0_RX_MATCH
#define UART_SCB__SPI_CTRL CYREG_SCB0_SPI_CTRL
#define UART_SCB__SPI_STATUS CYREG_SCB0_SPI_STATUS
#define UART_SCB__STATUS CYREG_SCB0_STATUS
#define UART_SCB__TX_CTRL CYREG_SCB0_TX_CTRL
#define UART_SCB__TX_FIFO_CTRL CYREG_SCB0_TX_FIFO_CTRL
#define UART_SCB__TX_FIFO_STATUS CYREG_SCB0_TX_FIFO_STATUS
#define UART_SCB__TX_FIFO_WR CYREG_SCB0_TX_FIFO_WR
#define UART_SCB__UART_CTRL CYREG_SCB0_UART_CTRL
#define UART_SCB__UART_RX_CTRL CYREG_SCB0_UART_RX_CTRL
#define UART_SCB__UART_RX_STATUS CYREG_SCB0_UART_RX_STATUS
#define UART_SCB__UART_TX_CTRL CYREG_SCB0_UART_TX_CTRL

/* UART_tx */
#define UART_tx__0__DM__MASK 0x38u
#define UART_tx__0__DM__SHIFT 3
#define UART_tx__0__DR CYREG_PRT4_DR
#define UART_tx__0__HSIOM CYREG_HSIOM_PORT_SEL4
#define UART_tx__0__HSIOM_MASK 0x000000F0u
#define UART_tx__0__HSIOM_SHIFT 4u
#define UART_tx__0__INTCFG CYREG_PRT4_INTCFG
#define UART_tx__0__INTSTAT CYREG_PRT4_INTSTAT
#define UART_tx__0__MASK 0x02u
#define UART_tx__0__PC CYREG_PRT4_PC
#define UART_tx__0__PC2 CYREG_PRT4_PC2
#define UART_tx__0__PORT 4u
#define UART_tx__0__PS CYREG_PRT4_PS
#define UART_tx__0__SHIFT 1
#define UART_tx__DR CYREG_PRT4_DR
#define UART_tx__INTCFG CYREG_PRT4_INTCFG
#define UART_tx__INTSTAT CYREG_PRT4_INTSTAT
#define UART_tx__MASK 0x02u
#define UART_tx__PC CYREG_PRT4_PC
#define UART_tx__PC2 CYREG_PRT4_PC2
#define UART_tx__PORT 4u
#define UART_tx__PS CYREG_PRT4_PS
#define UART_tx__SHIFT 1

/* Opamp_cy_psoc4_abuf */
#define Opamp_cy_psoc4_abuf__COMP_STAT CYREG_CTBM_COMP_STAT
#define Opamp_cy_psoc4_abuf__COMP_STAT_SHIFT 0
#define Opamp_cy_psoc4_abuf__CTBM_CTB_CTRL CYREG_CTBM_CTB_CTRL
#define Opamp_cy_psoc4_abuf__INTR CYREG_CTBM_INTR
#define Opamp_cy_psoc4_abuf__INTR_MASK CYREG_CTBM_INTR_MASK
#define Opamp_cy_psoc4_abuf__INTR_MASK_SHIFT 0
#define Opamp_cy_psoc4_abuf__INTR_MASKED CYREG_CTBM_INTR_MASKED
#define Opamp_cy_psoc4_abuf__INTR_MASKED_SHIFT 0
#define Opamp_cy_psoc4_abuf__INTR_SHIFT 0
#define Opamp_cy_psoc4_abuf__OA_COMP_TRIM CYREG_CTBM_OA0_COMP_TRIM
#define Opamp_cy_psoc4_abuf__OA_NUMBER 0u
#define Opamp_cy_psoc4_abuf__OA_OFFSET_TRIM CYREG_CTBM_OA0_OFFSET_TRIM
#define Opamp_cy_psoc4_abuf__OA_RES_CTRL CYREG_CTBM_OA_RES0_CTRL
#define Opamp_cy_psoc4_abuf__OA_SLOPE_OFFSET_TRIM CYREG_CTBM_OA0_SLOPE_OFFSET_TRIM

/* Clock_3 */
#define Clock_3__DIVIDER_MASK 0x0000FFFFu
#define Clock_3__ENABLE CYREG_CLK_DIVIDER_B00
#define Clock_3__ENABLE_MASK 0x80000000u
#define Clock_3__MASK 0x80000000u
#define Clock_3__REGISTER CYREG_CLK_DIVIDER_B00

/* Display_SPI_BSPIM */
#define Display_SPI_BSPIM_BitCounter__16BIT_CONTROL_AUX_CTL_REG CYREG_UDB_W16_ACTL_01
#define Display_SPI_BSPIM_BitCounter__16BIT_CONTROL_CONTROL_REG CYREG_UDB_W16_CTL_01
#define Display_SPI_BSPIM_BitCounter__16BIT_CONTROL_COUNT_REG CYREG_UDB_W16_CTL_01
#define Display_SPI_BSPIM_BitCounter__16BIT_COUNT_CONTROL_REG CYREG_UDB_W16_CTL_01
#define Display_SPI_BSPIM_BitCounter__16BIT_COUNT_COUNT_REG CYREG_UDB_W16_CTL_01
#define Display_SPI_BSPIM_BitCounter__16BIT_MASK_MASK_REG CYREG_UDB_W16_MSK_01
#define Display_SPI_BSPIM_BitCounter__16BIT_MASK_PERIOD_REG CYREG_UDB_W16_MSK_01
#define Display_SPI_BSPIM_BitCounter__16BIT_PERIOD_MASK_REG CYREG_UDB_W16_MSK_01
#define Display_SPI_BSPIM_BitCounter__16BIT_PERIOD_PERIOD_REG CYREG_UDB_W16_MSK_01
#define Display_SPI_BSPIM_BitCounter__CONTROL_AUX_CTL_REG CYREG_UDB_W8_ACTL_01
#define Display_SPI_BSPIM_BitCounter__CONTROL_REG CYREG_UDB_W8_CTL_01
#define Display_SPI_BSPIM_BitCounter__CONTROL_ST_REG CYREG_UDB_CAT16_CTL_ST_01
#define Display_SPI_BSPIM_BitCounter__COUNT_REG CYREG_UDB_W8_CTL_01
#define Display_SPI_BSPIM_BitCounter__COUNT_ST_REG CYREG_UDB_CAT16_CTL_ST_01
#define Display_SPI_BSPIM_BitCounter__MASK_CTL_AUX_CTL_REG CYREG_UDB_CAT16_ACTL_MSK_01
#define Display_SPI_BSPIM_BitCounter__PER_CTL_AUX_CTL_REG CYREG_UDB_CAT16_ACTL_MSK_01
#define Display_SPI_BSPIM_BitCounter__PERIOD_REG CYREG_UDB_W8_MSK_01
#define Display_SPI_BSPIM_BitCounter_ST__16BIT_STATUS_AUX_CTL_REG CYREG_UDB_W16_ACTL_01
#define Display_SPI_BSPIM_BitCounter_ST__16BIT_STATUS_REG CYREG_UDB_W16_ST_01
#define Display_SPI_BSPIM_BitCounter_ST__MASK_REG CYREG_UDB_W8_MSK_01
#define Display_SPI_BSPIM_BitCounter_ST__MASK_ST_AUX_CTL_REG CYREG_UDB_CAT16_ACTL_MSK_01
#define Display_SPI_BSPIM_BitCounter_ST__PER_ST_AUX_CTL_REG CYREG_UDB_CAT16_ACTL_MSK_01
#define Display_SPI_BSPIM_BitCounter_ST__STATUS_AUX_CTL_REG CYREG_UDB_W8_ACTL_01
#define Display_SPI_BSPIM_BitCounter_ST__STATUS_CNT_REG CYREG_UDB_CAT16_CTL_ST_01
#define Display_SPI_BSPIM_BitCounter_ST__STATUS_CONTROL_REG CYREG_UDB_CAT16_CTL_ST_01
#define Display_SPI_BSPIM_BitCounter_ST__STATUS_REG CYREG_UDB_W8_ST_01
#define Display_SPI_BSPIM_RxStsReg__4__MASK 0x10u
#define Display_SPI_BSPIM_RxStsReg__4__POS 4
#define Display_SPI_BSPIM_RxStsReg__5__MASK 0x20u
#define Display_SPI_BSPIM_RxStsReg__5__POS 5
#define Display_SPI_BSPIM_RxStsReg__6__MASK 0x40u
#define Display_SPI_BSPIM_RxStsReg__6__POS 6
#define Display_SPI_BSPIM_RxStsReg__MASK 0x70u
#define Display_SPI_BSPIM_RxStsReg__MASK_REG CYREG_UDB_W8_MSK_03
#define Display_SPI_BSPIM_RxStsReg__STATUS_AUX_CTL_REG CYREG_UDB_W8_ACTL_03
#define Display_SPI_BSPIM_RxStsReg__STATUS_REG CYREG_UDB_W8_ST_03
#define Display_SPI_BSPIM_sR8_Dp_u0__16BIT_A0_REG CYREG_UDB_W16_A0_01
#define Display_SPI_BSPIM_sR8_Dp_u0__16BIT_A1_REG CYREG_UDB_W16_A1_01
#define Display_SPI_BSPIM_sR8_Dp_u0__16BIT_D0_REG CYREG_UDB_W16_D0_01
#define Display_SPI_BSPIM_sR8_Dp_u0__16BIT_D1_REG CYREG_UDB_W16_D1_01
#define Display_SPI_BSPIM_sR8_Dp_u0__16BIT_DP_AUX_CTL_REG CYREG_UDB_W16_ACTL_01
#define Display_SPI_BSPIM_sR8_Dp_u0__16BIT_F0_REG CYREG_UDB_W16_F0_01
#define Display_SPI_BSPIM_sR8_Dp_u0__16BIT_F1_REG CYREG_UDB_W16_F1_01
#define Display_SPI_BSPIM_sR8_Dp_u0__A0_A1_REG CYREG_UDB_CAT16_A_01
#define Display_SPI_BSPIM_sR8_Dp_u0__A0_REG CYREG_UDB_W8_A0_01
#define Display_SPI_BSPIM_sR8_Dp_u0__A1_REG CYREG_UDB_W8_A1_01
#define Display_SPI_BSPIM_sR8_Dp_u0__D0_D1_REG CYREG_UDB_CAT16_D_01
#define Display_SPI_BSPIM_sR8_Dp_u0__D0_REG CYREG_UDB_W8_D0_01
#define Display_SPI_BSPIM_sR8_Dp_u0__D1_REG CYREG_UDB_W8_D1_01
#define Display_SPI_BSPIM_sR8_Dp_u0__DP_AUX_CTL_REG CYREG_UDB_W8_ACTL_01
#define Display_SPI_BSPIM_sR8_Dp_u0__F0_F1_REG CYREG_UDB_CAT16_F_01
#define Display_SPI_BSPIM_sR8_Dp_u0__F0_REG CYREG_UDB_W8_F0_01
#define Display_SPI_BSPIM_sR8_Dp_u0__F1_REG CYREG_UDB_W8_F1_01
#define Display_SPI_BSPIM_sR8_Dp_u0__MSK_DP_AUX_CTL_REG CYREG_UDB_CAT16_ACTL_MSK_01
#define Display_SPI_BSPIM_sR8_Dp_u0__PER_DP_AUX_CTL_REG CYREG_UDB_CAT16_ACTL_MSK_01
#define Display_SPI_BSPIM_TxStsReg__0__MASK 0x01u
#define Display_SPI_BSPIM_TxStsReg__0__POS 0
#define Display_SPI_BSPIM_TxStsReg__1__MASK 0x02u
#define Display_SPI_BSPIM_TxStsReg__1__POS 1
#define Display_SPI_BSPIM_TxStsReg__16BIT_STATUS_AUX_CTL_REG CYREG_UDB_W16_ACTL_02
#define Display_SPI_BSPIM_TxStsReg__16BIT_STATUS_REG CYREG_UDB_W16_ST_02
#define Display_SPI_BSPIM_TxStsReg__2__MASK 0x04u
#define Display_SPI_BSPIM_TxStsReg__2__POS 2
#define Display_SPI_BSPIM_TxStsReg__3__MASK 0x08u
#define Display_SPI_BSPIM_TxStsReg__3__POS 3
#define Display_SPI_BSPIM_TxStsReg__4__MASK 0x10u
#define Display_SPI_BSPIM_TxStsReg__4__POS 4
#define Display_SPI_BSPIM_TxStsReg__MASK 0x1Fu
#define Display_SPI_BSPIM_TxStsReg__MASK_REG CYREG_UDB_W8_MSK_02
#define Display_SPI_BSPIM_TxStsReg__MASK_ST_AUX_CTL_REG CYREG_UDB_CAT16_ACTL_MSK_02
#define Display_SPI_BSPIM_TxStsReg__PER_ST_AUX_CTL_REG CYREG_UDB_CAT16_ACTL_MSK_02
#define Display_SPI_BSPIM_TxStsReg__STATUS_AUX_CTL_REG CYREG_UDB_W8_ACTL_02
#define Display_SPI_BSPIM_TxStsReg__STATUS_CNT_REG CYREG_UDB_CAT16_CTL_ST_02
#define Display_SPI_BSPIM_TxStsReg__STATUS_CONTROL_REG CYREG_UDB_CAT16_CTL_ST_02
#define Display_SPI_BSPIM_TxStsReg__STATUS_REG CYREG_UDB_W8_ST_02

/* Display_SS_Reg */
#define Display_SS_Reg_Sync_ctrl_reg__0__MASK 0x01u
#define Display_SS_Reg_Sync_ctrl_reg__0__POS 0
#define Display_SS_Reg_Sync_ctrl_reg__16BIT_CONTROL_AUX_CTL_REG CYREG_UDB_W16_ACTL_02
#define Display_SS_Reg_Sync_ctrl_reg__16BIT_CONTROL_CONTROL_REG CYREG_UDB_W16_CTL_02
#define Display_SS_Reg_Sync_ctrl_reg__16BIT_CONTROL_COUNT_REG CYREG_UDB_W16_CTL_02
#define Display_SS_Reg_Sync_ctrl_reg__16BIT_COUNT_CONTROL_REG CYREG_UDB_W16_CTL_02
#define Display_SS_Reg_Sync_ctrl_reg__16BIT_COUNT_COUNT_REG CYREG_UDB_W16_CTL_02
#define Display_SS_Reg_Sync_ctrl_reg__16BIT_MASK_MASK_REG CYREG_UDB_W16_MSK_02
#define Display_SS_Reg_Sync_ctrl_reg__16BIT_MASK_PERIOD_REG CYREG_UDB_W16_MSK_02
#define Display_SS_Reg_Sync_ctrl_reg__16BIT_PERIOD_MASK_REG CYREG_UDB_W16_MSK_02
#define Display_SS_Reg_Sync_ctrl_reg__16BIT_PERIOD_PERIOD_REG CYREG_UDB_W16_MSK_02
#define Display_SS_Reg_Sync_ctrl_reg__CONTROL_AUX_CTL_REG CYREG_UDB_W8_ACTL_02
#define Display_SS_Reg_Sync_ctrl_reg__CONTROL_REG CYREG_UDB_W8_CTL_02
#define Display_SS_Reg_Sync_ctrl_reg__CONTROL_ST_REG CYREG_UDB_CAT16_CTL_ST_02
#define Display_SS_Reg_Sync_ctrl_reg__COUNT_REG CYREG_UDB_W8_CTL_02
#define Display_SS_Reg_Sync_ctrl_reg__COUNT_ST_REG CYREG_UDB_CAT16_CTL_ST_02
#define Display_SS_Reg_Sync_ctrl_reg__MASK 0x01u
#define Display_SS_Reg_Sync_ctrl_reg__MASK_CTL_AUX_CTL_REG CYREG_UDB_CAT16_ACTL_MSK_02
#define Display_SS_Reg_Sync_ctrl_reg__PER_CTL_AUX_CTL_REG CYREG_UDB_CAT16_ACTL_MSK_02
#define Display_SS_Reg_Sync_ctrl_reg__PERIOD_REG CYREG_UDB_W8_MSK_02

/* disp_ss */
#define disp_ss__0__DM__MASK 0x1C0u
#define disp_ss__0__DM__SHIFT 6
#define disp_ss__0__DR CYREG_PRT0_DR
#define disp_ss__0__HSIOM CYREG_HSIOM_PORT_SEL0
#define disp_ss__0__HSIOM_MASK 0x00000F00u
#define disp_ss__0__HSIOM_SHIFT 8u
#define disp_ss__0__INTCFG CYREG_PRT0_INTCFG
#define disp_ss__0__INTSTAT CYREG_PRT0_INTSTAT
#define disp_ss__0__MASK 0x04u
#define disp_ss__0__OUT_SEL CYREG_UDB_PA0_CFG10
#define disp_ss__0__OUT_SEL_SHIFT 4u
#define disp_ss__0__OUT_SEL_VAL 3u
#define disp_ss__0__PA__CFG0 CYREG_UDB_PA0_CFG0
#define disp_ss__0__PA__CFG1 CYREG_UDB_PA0_CFG1
#define disp_ss__0__PA__CFG10 CYREG_UDB_PA0_CFG10
#define disp_ss__0__PA__CFG11 CYREG_UDB_PA0_CFG11
#define disp_ss__0__PA__CFG12 CYREG_UDB_PA0_CFG12
#define disp_ss__0__PA__CFG13 CYREG_UDB_PA0_CFG13
#define disp_ss__0__PA__CFG14 CYREG_UDB_PA0_CFG14
#define disp_ss__0__PA__CFG2 CYREG_UDB_PA0_CFG2
#define disp_ss__0__PA__CFG3 CYREG_UDB_PA0_CFG3
#define disp_ss__0__PA__CFG4 CYREG_UDB_PA0_CFG4
#define disp_ss__0__PA__CFG5 CYREG_UDB_PA0_CFG5
#define disp_ss__0__PA__CFG6 CYREG_UDB_PA0_CFG6
#define disp_ss__0__PA__CFG7 CYREG_UDB_PA0_CFG7
#define disp_ss__0__PA__CFG8 CYREG_UDB_PA0_CFG8
#define disp_ss__0__PA__CFG9 CYREG_UDB_PA0_CFG9
#define disp_ss__0__PC CYREG_PRT0_PC
#define disp_ss__0__PC2 CYREG_PRT0_PC2
#define disp_ss__0__PORT 0u
#define disp_ss__0__PS CYREG_PRT0_PS
#define disp_ss__0__SHIFT 2
#define disp_ss__DR CYREG_PRT0_DR
#define disp_ss__INTCFG CYREG_PRT0_INTCFG
#define disp_ss__INTSTAT CYREG_PRT0_INTSTAT
#define disp_ss__MASK 0x04u
#define disp_ss__PA__CFG0 CYREG_UDB_PA0_CFG0
#define disp_ss__PA__CFG1 CYREG_UDB_PA0_CFG1
#define disp_ss__PA__CFG10 CYREG_UDB_PA0_CFG10
#define disp_ss__PA__CFG11 CYREG_UDB_PA0_CFG11
#define disp_ss__PA__CFG12 CYREG_UDB_PA0_CFG12
#define disp_ss__PA__CFG13 CYREG_UDB_PA0_CFG13
#define disp_ss__PA__CFG14 CYREG_UDB_PA0_CFG14
#define disp_ss__PA__CFG2 CYREG_UDB_PA0_CFG2
#define disp_ss__PA__CFG3 CYREG_UDB_PA0_CFG3
#define disp_ss__PA__CFG4 CYREG_UDB_PA0_CFG4
#define disp_ss__PA__CFG5 CYREG_UDB_PA0_CFG5
#define disp_ss__PA__CFG6 CYREG_UDB_PA0_CFG6
#define disp_ss__PA__CFG7 CYREG_UDB_PA0_CFG7
#define disp_ss__PA__CFG8 CYREG_UDB_PA0_CFG8
#define disp_ss__PA__CFG9 CYREG_UDB_PA0_CFG9
#define disp_ss__PC CYREG_PRT0_PC
#define disp_ss__PC2 CYREG_PRT0_PC2
#define disp_ss__PORT 0u
#define disp_ss__PS CYREG_PRT0_PS
#define disp_ss__SHIFT 2

/* IDAC_Low_cy_psoc4_idac */
#define IDAC_Low_cy_psoc4_idac__CSD_IDAC CYREG_CSD_IDAC
#define IDAC_Low_cy_psoc4_idac__CSD_IDAC_SHIFT 16
#define IDAC_Low_cy_psoc4_idac__CSD_TRIM1 CYREG_CSD_TRIM1
#define IDAC_Low_cy_psoc4_idac__CSD_TRIM1_SHIFT 4
#define IDAC_Low_cy_psoc4_idac__CSD_TRIM2 CYREG_CSD_TRIM2
#define IDAC_Low_cy_psoc4_idac__CSD_TRIM2_SHIFT 4
#define IDAC_Low_cy_psoc4_idac__IDAC_NUMBER 2u
#define IDAC_Low_cy_psoc4_idac__POLARITY CYREG_CSD_CONFIG
#define IDAC_Low_cy_psoc4_idac__POLARITY_SHIFT 17

/* Backlight */
#define Backlight__0__DM__MASK 0xE00000u
#define Backlight__0__DM__SHIFT 21
#define Backlight__0__DR CYREG_PRT0_DR
#define Backlight__0__HSIOM CYREG_HSIOM_PORT_SEL0
#define Backlight__0__HSIOM_MASK 0xF0000000u
#define Backlight__0__HSIOM_SHIFT 28u
#define Backlight__0__INTCFG CYREG_PRT0_INTCFG
#define Backlight__0__INTSTAT CYREG_PRT0_INTSTAT
#define Backlight__0__MASK 0x80u
#define Backlight__0__PA__CFG0 CYREG_UDB_PA0_CFG0
#define Backlight__0__PA__CFG1 CYREG_UDB_PA0_CFG1
#define Backlight__0__PA__CFG10 CYREG_UDB_PA0_CFG10
#define Backlight__0__PA__CFG11 CYREG_UDB_PA0_CFG11
#define Backlight__0__PA__CFG12 CYREG_UDB_PA0_CFG12
#define Backlight__0__PA__CFG13 CYREG_UDB_PA0_CFG13
#define Backlight__0__PA__CFG14 CYREG_UDB_PA0_CFG14
#define Backlight__0__PA__CFG2 CYREG_UDB_PA0_CFG2
#define Backlight__0__PA__CFG3 CYREG_UDB_PA0_CFG3
#define Backlight__0__PA__CFG4 CYREG_UDB_PA0_CFG4
#define Backlight__0__PA__CFG5 CYREG_UDB_PA0_CFG5
#define Backlight__0__PA__CFG6 CYREG_UDB_PA0_CFG6
#define Backlight__0__PA__CFG7 CYREG_UDB_PA0_CFG7
#define Backlight__0__PA__CFG8 CYREG_UDB_PA0_CFG8
#define Backlight__0__PA__CFG9 CYREG_UDB_PA0_CFG9
#define Backlight__0__PC CYREG_PRT0_PC
#define Backlight__0__PC2 CYREG_PRT0_PC2
#define Backlight__0__PORT 0u
#define Backlight__0__PS CYREG_PRT0_PS
#define Backlight__0__SHIFT 7
#define Backlight__DR CYREG_PRT0_DR
#define Backlight__INTCFG CYREG_PRT0_INTCFG
#define Backlight__INTSTAT CYREG_PRT0_INTSTAT
#define Backlight__MASK 0x80u
#define Backlight__PA__CFG0 CYREG_UDB_PA0_CFG0
#define Backlight__PA__CFG1 CYREG_UDB_PA0_CFG1
#define Backlight__PA__CFG10 CYREG_UDB_PA0_CFG10
#define Backlight__PA__CFG11 CYREG_UDB_PA0_CFG11
#define Backlight__PA__CFG12 CYREG_UDB_PA0_CFG12
#define Backlight__PA__CFG13 CYREG_UDB_PA0_CFG13
#define Backlight__PA__CFG14 CYREG_UDB_PA0_CFG14
#define Backlight__PA__CFG2 CYREG_UDB_PA0_CFG2
#define Backlight__PA__CFG3 CYREG_UDB_PA0_CFG3
#define Backlight__PA__CFG4 CYREG_UDB_PA0_CFG4
#define Backlight__PA__CFG5 CYREG_UDB_PA0_CFG5
#define Backlight__PA__CFG6 CYREG_UDB_PA0_CFG6
#define Backlight__PA__CFG7 CYREG_UDB_PA0_CFG7
#define Backlight__PA__CFG8 CYREG_UDB_PA0_CFG8
#define Backlight__PA__CFG9 CYREG_UDB_PA0_CFG9
#define Backlight__PC CYREG_PRT0_PC
#define Backlight__PC2 CYREG_PRT0_PC2
#define Backlight__PORT 0u
#define Backlight__PS CYREG_PRT0_PS
#define Backlight__SHIFT 7

/* IDAC_High_cy_psoc4_idac */
#define IDAC_High_cy_psoc4_idac__CSD_IDAC CYREG_CSD_IDAC
#define IDAC_High_cy_psoc4_idac__CSD_IDAC_SHIFT 0
#define IDAC_High_cy_psoc4_idac__CSD_TRIM1 CYREG_CSD_TRIM1
#define IDAC_High_cy_psoc4_idac__CSD_TRIM1_SHIFT 0
#define IDAC_High_cy_psoc4_idac__CSD_TRIM2 CYREG_CSD_TRIM2
#define IDAC_High_cy_psoc4_idac__CSD_TRIM2_SHIFT 0
#define IDAC_High_cy_psoc4_idac__IDAC_NUMBER 1u
#define IDAC_High_cy_psoc4_idac__POLARITY CYREG_CSD_CONFIG
#define IDAC_High_cy_psoc4_idac__POLARITY_SHIFT 16

/* Opamp_Out */
#define Opamp_Out__0__DM__MASK 0x1C0u
#define Opamp_Out__0__DM__SHIFT 6
#define Opamp_Out__0__DR CYREG_PRT1_DR
#define Opamp_Out__0__HSIOM CYREG_HSIOM_PORT_SEL1
#define Opamp_Out__0__HSIOM_MASK 0x00000F00u
#define Opamp_Out__0__HSIOM_SHIFT 8u
#define Opamp_Out__0__INTCFG CYREG_PRT1_INTCFG
#define Opamp_Out__0__INTSTAT CYREG_PRT1_INTSTAT
#define Opamp_Out__0__MASK 0x04u
#define Opamp_Out__0__PA__CFG0 CYREG_UDB_PA1_CFG0
#define Opamp_Out__0__PA__CFG1 CYREG_UDB_PA1_CFG1
#define Opamp_Out__0__PA__CFG10 CYREG_UDB_PA1_CFG10
#define Opamp_Out__0__PA__CFG11 CYREG_UDB_PA1_CFG11
#define Opamp_Out__0__PA__CFG12 CYREG_UDB_PA1_CFG12
#define Opamp_Out__0__PA__CFG13 CYREG_UDB_PA1_CFG13
#define Opamp_Out__0__PA__CFG14 CYREG_UDB_PA1_CFG14
#define Opamp_Out__0__PA__CFG2 CYREG_UDB_PA1_CFG2
#define Opamp_Out__0__PA__CFG3 CYREG_UDB_PA1_CFG3
#define Opamp_Out__0__PA__CFG4 CYREG_UDB_PA1_CFG4
#define Opamp_Out__0__PA__CFG5 CYREG_UDB_PA1_CFG5
#define Opamp_Out__0__PA__CFG6 CYREG_UDB_PA1_CFG6
#define Opamp_Out__0__PA__CFG7 CYREG_UDB_PA1_CFG7
#define Opamp_Out__0__PA__CFG8 CYREG_UDB_PA1_CFG8
#define Opamp_Out__0__PA__CFG9 CYREG_UDB_PA1_CFG9
#define Opamp_Out__0__PC CYREG_PRT1_PC
#define Opamp_Out__0__PC2 CYREG_PRT1_PC2
#define Opamp_Out__0__PORT 1u
#define Opamp_Out__0__PS CYREG_PRT1_PS
#define Opamp_Out__0__SHIFT 2
#define Opamp_Out__DR CYREG_PRT1_DR
#define Opamp_Out__INTCFG CYREG_PRT1_INTCFG
#define Opamp_Out__INTSTAT CYREG_PRT1_INTSTAT
#define Opamp_Out__MASK 0x04u
#define Opamp_Out__PA__CFG0 CYREG_UDB_PA1_CFG0
#define Opamp_Out__PA__CFG1 CYREG_UDB_PA1_CFG1
#define Opamp_Out__PA__CFG10 CYREG_UDB_PA1_CFG10
#define Opamp_Out__PA__CFG11 CYREG_UDB_PA1_CFG11
#define Opamp_Out__PA__CFG12 CYREG_UDB_PA1_CFG12
#define Opamp_Out__PA__CFG13 CYREG_UDB_PA1_CFG13
#define Opamp_Out__PA__CFG14 CYREG_UDB_PA1_CFG14
#define Opamp_Out__PA__CFG2 CYREG_UDB_PA1_CFG2
#define Opamp_Out__PA__CFG3 CYREG_UDB_PA1_CFG3
#define Opamp_Out__PA__CFG4 CYREG_UDB_PA1_CFG4
#define Opamp_Out__PA__CFG5 CYREG_UDB_PA1_CFG5
#define Opamp_Out__PA__CFG6 CYREG_UDB_PA1_CFG6
#define Opamp_Out__PA__CFG7 CYREG_UDB_PA1_CFG7
#define Opamp_Out__PA__CFG8 CYREG_UDB_PA1_CFG8
#define Opamp_Out__PA__CFG9 CYREG_UDB_PA1_CFG9
#define Opamp_Out__PC CYREG_PRT1_PC
#define Opamp_Out__PC2 CYREG_PRT1_PC2
#define Opamp_Out__PORT 1u
#define Opamp_Out__PS CYREG_PRT1_PS
#define Opamp_Out__SHIFT 2

/* disp_mosi */
#define disp_mosi__0__DM__MASK 0x1C0000u
#define disp_mosi__0__DM__SHIFT 18
#define disp_mosi__0__DR CYREG_PRT0_DR
#define disp_mosi__0__HSIOM CYREG_HSIOM_PORT_SEL0
#define disp_mosi__0__HSIOM_MASK 0x0F000000u
#define disp_mosi__0__HSIOM_SHIFT 24u
#define disp_mosi__0__INTCFG CYREG_PRT0_INTCFG
#define disp_mosi__0__INTSTAT CYREG_PRT0_INTSTAT
#define disp_mosi__0__MASK 0x40u
#define disp_mosi__0__OUT_SEL CYREG_UDB_PA0_CFG10
#define disp_mosi__0__OUT_SEL_SHIFT 12u
#define disp_mosi__0__OUT_SEL_VAL 1u
#define disp_mosi__0__PA__CFG0 CYREG_UDB_PA0_CFG0
#define disp_mosi__0__PA__CFG1 CYREG_UDB_PA0_CFG1
#define disp_mosi__0__PA__CFG10 CYREG_UDB_PA0_CFG10
#define disp_mosi__0__PA__CFG11 CYREG_UDB_PA0_CFG11
#define disp_mosi__0__PA__CFG12 CYREG_UDB_PA0_CFG12
#define disp_mosi__0__PA__CFG13 CYREG_UDB_PA0_CFG13
#define disp_mosi__0__PA__CFG14 CYREG_UDB_PA0_CFG14
#define disp_mosi__0__PA__CFG2 CYREG_UDB_PA0_CFG2
#define disp_mosi__0__PA__CFG3 CYREG_UDB_PA0_CFG3
#define disp_mosi__0__PA__CFG4 CYREG_UDB_PA0_CFG4
#define disp_mosi__0__PA__CFG5 CYREG_UDB_PA0_CFG5
#define disp_mosi__0__PA__CFG6 CYREG_UDB_PA0_CFG6
#define disp_mosi__0__PA__CFG7 CYREG_UDB_PA0_CFG7
#define disp_mosi__0__PA__CFG8 CYREG_UDB_PA0_CFG8
#define disp_mosi__0__PA__CFG9 CYREG_UDB_PA0_CFG9
#define disp_mosi__0__PC CYREG_PRT0_PC
#define disp_mosi__0__PC2 CYREG_PRT0_PC2
#define disp_mosi__0__PORT 0u
#define disp_mosi__0__PS CYREG_PRT0_PS
#define disp_mosi__0__SHIFT 6
#define disp_mosi__DR CYREG_PRT0_DR
#define disp_mosi__INTCFG CYREG_PRT0_INTCFG
#define disp_mosi__INTSTAT CYREG_PRT0_INTSTAT
#define disp_mosi__MASK 0x40u
#define disp_mosi__PA__CFG0 CYREG_UDB_PA0_CFG0
#define disp_mosi__PA__CFG1 CYREG_UDB_PA0_CFG1
#define disp_mosi__PA__CFG10 CYREG_UDB_PA0_CFG10
#define disp_mosi__PA__CFG11 CYREG_UDB_PA0_CFG11
#define disp_mosi__PA__CFG12 CYREG_UDB_PA0_CFG12
#define disp_mosi__PA__CFG13 CYREG_UDB_PA0_CFG13
#define disp_mosi__PA__CFG14 CYREG_UDB_PA0_CFG14
#define disp_mosi__PA__CFG2 CYREG_UDB_PA0_CFG2
#define disp_mosi__PA__CFG3 CYREG_UDB_PA0_CFG3
#define disp_mosi__PA__CFG4 CYREG_UDB_PA0_CFG4
#define disp_mosi__PA__CFG5 CYREG_UDB_PA0_CFG5
#define disp_mosi__PA__CFG6 CYREG_UDB_PA0_CFG6
#define disp_mosi__PA__CFG7 CYREG_UDB_PA0_CFG7
#define disp_mosi__PA__CFG8 CYREG_UDB_PA0_CFG8
#define disp_mosi__PA__CFG9 CYREG_UDB_PA0_CFG9
#define disp_mosi__PC CYREG_PRT0_PC
#define disp_mosi__PC2 CYREG_PRT0_PC2
#define disp_mosi__PORT 0u
#define disp_mosi__PS CYREG_PRT0_PS
#define disp_mosi__SHIFT 6

/* disp_sclk */
#define disp_sclk__0__DM__MASK 0xE00u
#define disp_sclk__0__DM__SHIFT 9
#define disp_sclk__0__DR CYREG_PRT0_DR
#define disp_sclk__0__HSIOM CYREG_HSIOM_PORT_SEL0
#define disp_sclk__0__HSIOM_MASK 0x0000F000u
#define disp_sclk__0__HSIOM_SHIFT 12u
#define disp_sclk__0__INTCFG CYREG_PRT0_INTCFG
#define disp_sclk__0__INTSTAT CYREG_PRT0_INTSTAT
#define disp_sclk__0__MASK 0x08u
#define disp_sclk__0__OUT_SEL CYREG_UDB_PA0_CFG10
#define disp_sclk__0__OUT_SEL_SHIFT 6u
#define disp_sclk__0__OUT_SEL_VAL 1u
#define disp_sclk__0__PA__CFG0 CYREG_UDB_PA0_CFG0
#define disp_sclk__0__PA__CFG1 CYREG_UDB_PA0_CFG1
#define disp_sclk__0__PA__CFG10 CYREG_UDB_PA0_CFG10
#define disp_sclk__0__PA__CFG11 CYREG_UDB_PA0_CFG11
#define disp_sclk__0__PA__CFG12 CYREG_UDB_PA0_CFG12
#define disp_sclk__0__PA__CFG13 CYREG_UDB_PA0_CFG13
#define disp_sclk__0__PA__CFG14 CYREG_UDB_PA0_CFG14
#define disp_sclk__0__PA__CFG2 CYREG_UDB_PA0_CFG2
#define disp_sclk__0__PA__CFG3 CYREG_UDB_PA0_CFG3
#define disp_sclk__0__PA__CFG4 CYREG_UDB_PA0_CFG4
#define disp_sclk__0__PA__CFG5 CYREG_UDB_PA0_CFG5
#define disp_sclk__0__PA__CFG6 CYREG_UDB_PA0_CFG6
#define disp_sclk__0__PA__CFG7 CYREG_UDB_PA0_CFG7
#define disp_sclk__0__PA__CFG8 CYREG_UDB_PA0_CFG8
#define disp_sclk__0__PA__CFG9 CYREG_UDB_PA0_CFG9
#define disp_sclk__0__PC CYREG_PRT0_PC
#define disp_sclk__0__PC2 CYREG_PRT0_PC2
#define disp_sclk__0__PORT 0u
#define disp_sclk__0__PS CYREG_PRT0_PS
#define disp_sclk__0__SHIFT 3
#define disp_sclk__DR CYREG_PRT0_DR
#define disp_sclk__INTCFG CYREG_PRT0_INTCFG
#define disp_sclk__INTSTAT CYREG_PRT0_INTSTAT
#define disp_sclk__MASK 0x08u
#define disp_sclk__PA__CFG0 CYREG_UDB_PA0_CFG0
#define disp_sclk__PA__CFG1 CYREG_UDB_PA0_CFG1
#define disp_sclk__PA__CFG10 CYREG_UDB_PA0_CFG10
#define disp_sclk__PA__CFG11 CYREG_UDB_PA0_CFG11
#define disp_sclk__PA__CFG12 CYREG_UDB_PA0_CFG12
#define disp_sclk__PA__CFG13 CYREG_UDB_PA0_CFG13
#define disp_sclk__PA__CFG14 CYREG_UDB_PA0_CFG14
#define disp_sclk__PA__CFG2 CYREG_UDB_PA0_CFG2
#define disp_sclk__PA__CFG3 CYREG_UDB_PA0_CFG3
#define disp_sclk__PA__CFG4 CYREG_UDB_PA0_CFG4
#define disp_sclk__PA__CFG5 CYREG_UDB_PA0_CFG5
#define disp_sclk__PA__CFG6 CYREG_UDB_PA0_CFG6
#define disp_sclk__PA__CFG7 CYREG_UDB_PA0_CFG7
#define disp_sclk__PA__CFG8 CYREG_UDB_PA0_CFG8
#define disp_sclk__PA__CFG9 CYREG_UDB_PA0_CFG9
#define disp_sclk__PC CYREG_PRT0_PC
#define disp_sclk__PC2 CYREG_PRT0_PC2
#define disp_sclk__PORT 0u
#define disp_sclk__PS CYREG_PRT0_PS
#define disp_sclk__SHIFT 3

/* opamp_neg */
#define opamp_neg__0__DM__MASK 0x38u
#define opamp_neg__0__DM__SHIFT 3
#define opamp_neg__0__DR CYREG_PRT1_DR
#define opamp_neg__0__HSIOM CYREG_HSIOM_PORT_SEL1
#define opamp_neg__0__HSIOM_MASK 0x000000F0u
#define opamp_neg__0__HSIOM_SHIFT 4u
#define opamp_neg__0__INTCFG CYREG_PRT1_INTCFG
#define opamp_neg__0__INTSTAT CYREG_PRT1_INTSTAT
#define opamp_neg__0__MASK 0x02u
#define opamp_neg__0__PA__CFG0 CYREG_UDB_PA1_CFG0
#define opamp_neg__0__PA__CFG1 CYREG_UDB_PA1_CFG1
#define opamp_neg__0__PA__CFG10 CYREG_UDB_PA1_CFG10
#define opamp_neg__0__PA__CFG11 CYREG_UDB_PA1_CFG11
#define opamp_neg__0__PA__CFG12 CYREG_UDB_PA1_CFG12
#define opamp_neg__0__PA__CFG13 CYREG_UDB_PA1_CFG13
#define opamp_neg__0__PA__CFG14 CYREG_UDB_PA1_CFG14
#define opamp_neg__0__PA__CFG2 CYREG_UDB_PA1_CFG2
#define opamp_neg__0__PA__CFG3 CYREG_UDB_PA1_CFG3
#define opamp_neg__0__PA__CFG4 CYREG_UDB_PA1_CFG4
#define opamp_neg__0__PA__CFG5 CYREG_UDB_PA1_CFG5
#define opamp_neg__0__PA__CFG6 CYREG_UDB_PA1_CFG6
#define opamp_neg__0__PA__CFG7 CYREG_UDB_PA1_CFG7
#define opamp_neg__0__PA__CFG8 CYREG_UDB_PA1_CFG8
#define opamp_neg__0__PA__CFG9 CYREG_UDB_PA1_CFG9
#define opamp_neg__0__PC CYREG_PRT1_PC
#define opamp_neg__0__PC2 CYREG_PRT1_PC2
#define opamp_neg__0__PORT 1u
#define opamp_neg__0__PS CYREG_PRT1_PS
#define opamp_neg__0__SHIFT 1
#define opamp_neg__DR CYREG_PRT1_DR
#define opamp_neg__INTCFG CYREG_PRT1_INTCFG
#define opamp_neg__INTSTAT CYREG_PRT1_INTSTAT
#define opamp_neg__MASK 0x02u
#define opamp_neg__PA__CFG0 CYREG_UDB_PA1_CFG0
#define opamp_neg__PA__CFG1 CYREG_UDB_PA1_CFG1
#define opamp_neg__PA__CFG10 CYREG_UDB_PA1_CFG10
#define opamp_neg__PA__CFG11 CYREG_UDB_PA1_CFG11
#define opamp_neg__PA__CFG12 CYREG_UDB_PA1_CFG12
#define opamp_neg__PA__CFG13 CYREG_UDB_PA1_CFG13
#define opamp_neg__PA__CFG14 CYREG_UDB_PA1_CFG14
#define opamp_neg__PA__CFG2 CYREG_UDB_PA1_CFG2
#define opamp_neg__PA__CFG3 CYREG_UDB_PA1_CFG3
#define opamp_neg__PA__CFG4 CYREG_UDB_PA1_CFG4
#define opamp_neg__PA__CFG5 CYREG_UDB_PA1_CFG5
#define opamp_neg__PA__CFG6 CYREG_UDB_PA1_CFG6
#define opamp_neg__PA__CFG7 CYREG_UDB_PA1_CFG7
#define opamp_neg__PA__CFG8 CYREG_UDB_PA1_CFG8
#define opamp_neg__PA__CFG9 CYREG_UDB_PA1_CFG9
#define opamp_neg__PC CYREG_PRT1_PC
#define opamp_neg__PC2 CYREG_PRT1_PC2
#define opamp_neg__PORT 1u
#define opamp_neg__PS CYREG_PRT1_PS
#define opamp_neg__SHIFT 1

/* opamp_pos */
#define opamp_pos__0__DM__MASK 0x07u
#define opamp_pos__0__DM__SHIFT 0
#define opamp_pos__0__DR CYREG_PRT1_DR
#define opamp_pos__0__HSIOM CYREG_HSIOM_PORT_SEL1
#define opamp_pos__0__HSIOM_MASK 0x0000000Fu
#define opamp_pos__0__HSIOM_SHIFT 0u
#define opamp_pos__0__INTCFG CYREG_PRT1_INTCFG
#define opamp_pos__0__INTSTAT CYREG_PRT1_INTSTAT
#define opamp_pos__0__MASK 0x01u
#define opamp_pos__0__PA__CFG0 CYREG_UDB_PA1_CFG0
#define opamp_pos__0__PA__CFG1 CYREG_UDB_PA1_CFG1
#define opamp_pos__0__PA__CFG10 CYREG_UDB_PA1_CFG10
#define opamp_pos__0__PA__CFG11 CYREG_UDB_PA1_CFG11
#define opamp_pos__0__PA__CFG12 CYREG_UDB_PA1_CFG12
#define opamp_pos__0__PA__CFG13 CYREG_UDB_PA1_CFG13
#define opamp_pos__0__PA__CFG14 CYREG_UDB_PA1_CFG14
#define opamp_pos__0__PA__CFG2 CYREG_UDB_PA1_CFG2
#define opamp_pos__0__PA__CFG3 CYREG_UDB_PA1_CFG3
#define opamp_pos__0__PA__CFG4 CYREG_UDB_PA1_CFG4
#define opamp_pos__0__PA__CFG5 CYREG_UDB_PA1_CFG5
#define opamp_pos__0__PA__CFG6 CYREG_UDB_PA1_CFG6
#define opamp_pos__0__PA__CFG7 CYREG_UDB_PA1_CFG7
#define opamp_pos__0__PA__CFG8 CYREG_UDB_PA1_CFG8
#define opamp_pos__0__PA__CFG9 CYREG_UDB_PA1_CFG9
#define opamp_pos__0__PC CYREG_PRT1_PC
#define opamp_pos__0__PC2 CYREG_PRT1_PC2
#define opamp_pos__0__PORT 1u
#define opamp_pos__0__PS CYREG_PRT1_PS
#define opamp_pos__0__SHIFT 0
#define opamp_pos__DR CYREG_PRT1_DR
#define opamp_pos__INTCFG CYREG_PRT1_INTCFG
#define opamp_pos__INTSTAT CYREG_PRT1_INTSTAT
#define opamp_pos__MASK 0x01u
#define opamp_pos__PA__CFG0 CYREG_UDB_PA1_CFG0
#define opamp_pos__PA__CFG1 CYREG_UDB_PA1_CFG1
#define opamp_pos__PA__CFG10 CYREG_UDB_PA1_CFG10
#define opamp_pos__PA__CFG11 CYREG_UDB_PA1_CFG11
#define opamp_pos__PA__CFG12 CYREG_UDB_PA1_CFG12
#define opamp_pos__PA__CFG13 CYREG_UDB_PA1_CFG13
#define opamp_pos__PA__CFG14 CYREG_UDB_PA1_CFG14
#define opamp_pos__PA__CFG2 CYREG_UDB_PA1_CFG2
#define opamp_pos__PA__CFG3 CYREG_UDB_PA1_CFG3
#define opamp_pos__PA__CFG4 CYREG_UDB_PA1_CFG4
#define opamp_pos__PA__CFG5 CYREG_UDB_PA1_CFG5
#define opamp_pos__PA__CFG6 CYREG_UDB_PA1_CFG6
#define opamp_pos__PA__CFG7 CYREG_UDB_PA1_CFG7
#define opamp_pos__PA__CFG8 CYREG_UDB_PA1_CFG8
#define opamp_pos__PA__CFG9 CYREG_UDB_PA1_CFG9
#define opamp_pos__PC CYREG_PRT1_PC
#define opamp_pos__PC2 CYREG_PRT1_PC2
#define opamp_pos__PORT 1u
#define opamp_pos__PS CYREG_PRT1_PS
#define opamp_pos__SHIFT 0

/* opamp_pos_sense */
#define opamp_pos_sense__0__DM__MASK 0x38000u
#define opamp_pos_sense__0__DM__SHIFT 15
#define opamp_pos_sense__0__DR CYREG_PRT2_DR
#define opamp_pos_sense__0__HSIOM CYREG_HSIOM_PORT_SEL2
#define opamp_pos_sense__0__HSIOM_MASK 0x00F00000u
#define opamp_pos_sense__0__HSIOM_SHIFT 20u
#define opamp_pos_sense__0__INTCFG CYREG_PRT2_INTCFG
#define opamp_pos_sense__0__INTSTAT CYREG_PRT2_INTSTAT
#define opamp_pos_sense__0__MASK 0x20u
#define opamp_pos_sense__0__PA__CFG0 CYREG_UDB_PA2_CFG0
#define opamp_pos_sense__0__PA__CFG1 CYREG_UDB_PA2_CFG1
#define opamp_pos_sense__0__PA__CFG10 CYREG_UDB_PA2_CFG10
#define opamp_pos_sense__0__PA__CFG11 CYREG_UDB_PA2_CFG11
#define opamp_pos_sense__0__PA__CFG12 CYREG_UDB_PA2_CFG12
#define opamp_pos_sense__0__PA__CFG13 CYREG_UDB_PA2_CFG13
#define opamp_pos_sense__0__PA__CFG14 CYREG_UDB_PA2_CFG14
#define opamp_pos_sense__0__PA__CFG2 CYREG_UDB_PA2_CFG2
#define opamp_pos_sense__0__PA__CFG3 CYREG_UDB_PA2_CFG3
#define opamp_pos_sense__0__PA__CFG4 CYREG_UDB_PA2_CFG4
#define opamp_pos_sense__0__PA__CFG5 CYREG_UDB_PA2_CFG5
#define opamp_pos_sense__0__PA__CFG6 CYREG_UDB_PA2_CFG6
#define opamp_pos_sense__0__PA__CFG7 CYREG_UDB_PA2_CFG7
#define opamp_pos_sense__0__PA__CFG8 CYREG_UDB_PA2_CFG8
#define opamp_pos_sense__0__PA__CFG9 CYREG_UDB_PA2_CFG9
#define opamp_pos_sense__0__PC CYREG_PRT2_PC
#define opamp_pos_sense__0__PC2 CYREG_PRT2_PC2
#define opamp_pos_sense__0__PORT 2u
#define opamp_pos_sense__0__PS CYREG_PRT2_PS
#define opamp_pos_sense__0__SHIFT 5
#define opamp_pos_sense__DR CYREG_PRT2_DR
#define opamp_pos_sense__INTCFG CYREG_PRT2_INTCFG
#define opamp_pos_sense__INTSTAT CYREG_PRT2_INTSTAT
#define opamp_pos_sense__MASK 0x20u
#define opamp_pos_sense__PA__CFG0 CYREG_UDB_PA2_CFG0
#define opamp_pos_sense__PA__CFG1 CYREG_UDB_PA2_CFG1
#define opamp_pos_sense__PA__CFG10 CYREG_UDB_PA2_CFG10
#define opamp_pos_sense__PA__CFG11 CYREG_UDB_PA2_CFG11
#define opamp_pos_sense__PA__CFG12 CYREG_UDB_PA2_CFG12
#define opamp_pos_sense__PA__CFG13 CYREG_UDB_PA2_CFG13
#define opamp_pos_sense__PA__CFG14 CYREG_UDB_PA2_CFG14
#define opamp_pos_sense__PA__CFG2 CYREG_UDB_PA2_CFG2
#define opamp_pos_sense__PA__CFG3 CYREG_UDB_PA2_CFG3
#define opamp_pos_sense__PA__CFG4 CYREG_UDB_PA2_CFG4
#define opamp_pos_sense__PA__CFG5 CYREG_UDB_PA2_CFG5
#define opamp_pos_sense__PA__CFG6 CYREG_UDB_PA2_CFG6
#define opamp_pos_sense__PA__CFG7 CYREG_UDB_PA2_CFG7
#define opamp_pos_sense__PA__CFG8 CYREG_UDB_PA2_CFG8
#define opamp_pos_sense__PA__CFG9 CYREG_UDB_PA2_CFG9
#define opamp_pos_sense__PC CYREG_PRT2_PC
#define opamp_pos_sense__PC2 CYREG_PRT2_PC2
#define opamp_pos_sense__PORT 2u
#define opamp_pos_sense__PS CYREG_PRT2_PS
#define opamp_pos_sense__SHIFT 5

/* QuadButton */
#define QuadButton__0__DM__MASK 0xE00u
#define QuadButton__0__DM__SHIFT 9
#define QuadButton__0__DR CYREG_PRT4_DR
#define QuadButton__0__HSIOM CYREG_HSIOM_PORT_SEL4
#define QuadButton__0__HSIOM_MASK 0x0000F000u
#define QuadButton__0__HSIOM_SHIFT 12u
#define QuadButton__0__INTCFG CYREG_PRT4_INTCFG
#define QuadButton__0__INTSTAT CYREG_PRT4_INTSTAT
#define QuadButton__0__MASK 0x08u
#define QuadButton__0__PC CYREG_PRT4_PC
#define QuadButton__0__PC2 CYREG_PRT4_PC2
#define QuadButton__0__PORT 4u
#define QuadButton__0__PS CYREG_PRT4_PS
#define QuadButton__0__SHIFT 3
#define QuadButton__DR CYREG_PRT4_DR
#define QuadButton__INTCFG CYREG_PRT4_INTCFG
#define QuadButton__INTSTAT CYREG_PRT4_INTSTAT
#define QuadButton__MASK 0x08u
#define QuadButton__PC CYREG_PRT4_PC
#define QuadButton__PC2 CYREG_PRT4_PC2
#define QuadButton__PORT 4u
#define QuadButton__PS CYREG_PRT4_PS
#define QuadButton__SHIFT 3
#define QuadButton__SNAP CYREG_PRT4_INTSTAT

/* Quadrature */
#define Quadrature__0__DM__MASK 0x07u
#define Quadrature__0__DM__SHIFT 0
#define Quadrature__0__DR CYREG_PRT0_DR
#define Quadrature__0__HSIOM CYREG_HSIOM_PORT_SEL0
#define Quadrature__0__HSIOM_MASK 0x0000000Fu
#define Quadrature__0__HSIOM_SHIFT 0u
#define Quadrature__0__INTCFG CYREG_PRT0_INTCFG
#define Quadrature__0__INTSTAT CYREG_PRT0_INTSTAT
#define Quadrature__0__MASK 0x01u
#define Quadrature__0__PA__CFG0 CYREG_UDB_PA0_CFG0
#define Quadrature__0__PA__CFG1 CYREG_UDB_PA0_CFG1
#define Quadrature__0__PA__CFG10 CYREG_UDB_PA0_CFG10
#define Quadrature__0__PA__CFG11 CYREG_UDB_PA0_CFG11
#define Quadrature__0__PA__CFG12 CYREG_UDB_PA0_CFG12
#define Quadrature__0__PA__CFG13 CYREG_UDB_PA0_CFG13
#define Quadrature__0__PA__CFG14 CYREG_UDB_PA0_CFG14
#define Quadrature__0__PA__CFG2 CYREG_UDB_PA0_CFG2
#define Quadrature__0__PA__CFG3 CYREG_UDB_PA0_CFG3
#define Quadrature__0__PA__CFG4 CYREG_UDB_PA0_CFG4
#define Quadrature__0__PA__CFG5 CYREG_UDB_PA0_CFG5
#define Quadrature__0__PA__CFG6 CYREG_UDB_PA0_CFG6
#define Quadrature__0__PA__CFG7 CYREG_UDB_PA0_CFG7
#define Quadrature__0__PA__CFG8 CYREG_UDB_PA0_CFG8
#define Quadrature__0__PA__CFG9 CYREG_UDB_PA0_CFG9
#define Quadrature__0__PC CYREG_PRT0_PC
#define Quadrature__0__PC2 CYREG_PRT0_PC2
#define Quadrature__0__PORT 0u
#define Quadrature__0__PS CYREG_PRT0_PS
#define Quadrature__0__SHIFT 0
#define Quadrature__1__DM__MASK 0x38u
#define Quadrature__1__DM__SHIFT 3
#define Quadrature__1__DR CYREG_PRT0_DR
#define Quadrature__1__HSIOM CYREG_HSIOM_PORT_SEL0
#define Quadrature__1__HSIOM_MASK 0x000000F0u
#define Quadrature__1__HSIOM_SHIFT 4u
#define Quadrature__1__INTCFG CYREG_PRT0_INTCFG
#define Quadrature__1__INTSTAT CYREG_PRT0_INTSTAT
#define Quadrature__1__MASK 0x02u
#define Quadrature__1__PA__CFG0 CYREG_UDB_PA0_CFG0
#define Quadrature__1__PA__CFG1 CYREG_UDB_PA0_CFG1
#define Quadrature__1__PA__CFG10 CYREG_UDB_PA0_CFG10
#define Quadrature__1__PA__CFG11 CYREG_UDB_PA0_CFG11
#define Quadrature__1__PA__CFG12 CYREG_UDB_PA0_CFG12
#define Quadrature__1__PA__CFG13 CYREG_UDB_PA0_CFG13
#define Quadrature__1__PA__CFG14 CYREG_UDB_PA0_CFG14
#define Quadrature__1__PA__CFG2 CYREG_UDB_PA0_CFG2
#define Quadrature__1__PA__CFG3 CYREG_UDB_PA0_CFG3
#define Quadrature__1__PA__CFG4 CYREG_UDB_PA0_CFG4
#define Quadrature__1__PA__CFG5 CYREG_UDB_PA0_CFG5
#define Quadrature__1__PA__CFG6 CYREG_UDB_PA0_CFG6
#define Quadrature__1__PA__CFG7 CYREG_UDB_PA0_CFG7
#define Quadrature__1__PA__CFG8 CYREG_UDB_PA0_CFG8
#define Quadrature__1__PA__CFG9 CYREG_UDB_PA0_CFG9
#define Quadrature__1__PC CYREG_PRT0_PC
#define Quadrature__1__PC2 CYREG_PRT0_PC2
#define Quadrature__1__PORT 0u
#define Quadrature__1__PS CYREG_PRT0_PS
#define Quadrature__1__SHIFT 1
#define Quadrature__DR CYREG_PRT0_DR
#define Quadrature__INTCFG CYREG_PRT0_INTCFG
#define Quadrature__INTSTAT CYREG_PRT0_INTSTAT
#define Quadrature__MASK 0x03u
#define Quadrature__PA__CFG0 CYREG_UDB_PA0_CFG0
#define Quadrature__PA__CFG1 CYREG_UDB_PA0_CFG1
#define Quadrature__PA__CFG10 CYREG_UDB_PA0_CFG10
#define Quadrature__PA__CFG11 CYREG_UDB_PA0_CFG11
#define Quadrature__PA__CFG12 CYREG_UDB_PA0_CFG12
#define Quadrature__PA__CFG13 CYREG_UDB_PA0_CFG13
#define Quadrature__PA__CFG14 CYREG_UDB_PA0_CFG14
#define Quadrature__PA__CFG2 CYREG_UDB_PA0_CFG2
#define Quadrature__PA__CFG3 CYREG_UDB_PA0_CFG3
#define Quadrature__PA__CFG4 CYREG_UDB_PA0_CFG4
#define Quadrature__PA__CFG5 CYREG_UDB_PA0_CFG5
#define Quadrature__PA__CFG6 CYREG_UDB_PA0_CFG6
#define Quadrature__PA__CFG7 CYREG_UDB_PA0_CFG7
#define Quadrature__PA__CFG8 CYREG_UDB_PA0_CFG8
#define Quadrature__PA__CFG9 CYREG_UDB_PA0_CFG9
#define Quadrature__PC CYREG_PRT0_PC
#define Quadrature__PC2 CYREG_PRT0_PC2
#define Quadrature__PORT 0u
#define Quadrature__PS CYREG_PRT0_PS
#define Quadrature__SHIFT 0
#define Quadrature__SNAP CYREG_PRT0_INTSTAT

/* disp_reset */
#define disp_reset__0__DM__MASK 0x1C0u
#define disp_reset__0__DM__SHIFT 6
#define disp_reset__0__DR CYREG_PRT4_DR
#define disp_reset__0__HSIOM CYREG_HSIOM_PORT_SEL4
#define disp_reset__0__HSIOM_MASK 0x00000F00u
#define disp_reset__0__HSIOM_SHIFT 8u
#define disp_reset__0__INTCFG CYREG_PRT4_INTCFG
#define disp_reset__0__INTSTAT CYREG_PRT4_INTSTAT
#define disp_reset__0__MASK 0x04u
#define disp_reset__0__PC CYREG_PRT4_PC
#define disp_reset__0__PC2 CYREG_PRT4_PC2
#define disp_reset__0__PORT 4u
#define disp_reset__0__PS CYREG_PRT4_PS
#define disp_reset__0__SHIFT 2
#define disp_reset__DR CYREG_PRT4_DR
#define disp_reset__INTCFG CYREG_PRT4_INTCFG
#define disp_reset__INTSTAT CYREG_PRT4_INTSTAT
#define disp_reset__MASK 0x04u
#define disp_reset__PC CYREG_PRT4_PC
#define disp_reset__PC2 CYREG_PRT4_PC2
#define disp_reset__PORT 4u
#define disp_reset__PS CYREG_PRT4_PS
#define disp_reset__SHIFT 2

/* idac_hi_out */
#define idac_hi_out__0__DM__MASK 0x07u
#define idac_hi_out__0__DM__SHIFT 0
#define idac_hi_out__0__DR CYREG_PRT3_DR
#define idac_hi_out__0__HSIOM CYREG_HSIOM_PORT_SEL3
#define idac_hi_out__0__HSIOM_MASK 0x0000000Fu
#define idac_hi_out__0__HSIOM_SHIFT 0u
#define idac_hi_out__0__INTCFG CYREG_PRT3_INTCFG
#define idac_hi_out__0__INTSTAT CYREG_PRT3_INTSTAT
#define idac_hi_out__0__MASK 0x01u
#define idac_hi_out__0__OUT_SEL CYREG_UDB_PA3_CFG10
#define idac_hi_out__0__OUT_SEL_SHIFT 0u
#define idac_hi_out__0__OUT_SEL_VAL 3u
#define idac_hi_out__0__PA__CFG0 CYREG_UDB_PA3_CFG0
#define idac_hi_out__0__PA__CFG1 CYREG_UDB_PA3_CFG1
#define idac_hi_out__0__PA__CFG10 CYREG_UDB_PA3_CFG10
#define idac_hi_out__0__PA__CFG11 CYREG_UDB_PA3_CFG11
#define idac_hi_out__0__PA__CFG12 CYREG_UDB_PA3_CFG12
#define idac_hi_out__0__PA__CFG13 CYREG_UDB_PA3_CFG13
#define idac_hi_out__0__PA__CFG14 CYREG_UDB_PA3_CFG14
#define idac_hi_out__0__PA__CFG2 CYREG_UDB_PA3_CFG2
#define idac_hi_out__0__PA__CFG3 CYREG_UDB_PA3_CFG3
#define idac_hi_out__0__PA__CFG4 CYREG_UDB_PA3_CFG4
#define idac_hi_out__0__PA__CFG5 CYREG_UDB_PA3_CFG5
#define idac_hi_out__0__PA__CFG6 CYREG_UDB_PA3_CFG6
#define idac_hi_out__0__PA__CFG7 CYREG_UDB_PA3_CFG7
#define idac_hi_out__0__PA__CFG8 CYREG_UDB_PA3_CFG8
#define idac_hi_out__0__PA__CFG9 CYREG_UDB_PA3_CFG9
#define idac_hi_out__0__PC CYREG_PRT3_PC
#define idac_hi_out__0__PC2 CYREG_PRT3_PC2
#define idac_hi_out__0__PORT 3u
#define idac_hi_out__0__PS CYREG_PRT3_PS
#define idac_hi_out__0__SHIFT 0
#define idac_hi_out__DR CYREG_PRT3_DR
#define idac_hi_out__INTCFG CYREG_PRT3_INTCFG
#define idac_hi_out__INTSTAT CYREG_PRT3_INTSTAT
#define idac_hi_out__MASK 0x01u
#define idac_hi_out__PA__CFG0 CYREG_UDB_PA3_CFG0
#define idac_hi_out__PA__CFG1 CYREG_UDB_PA3_CFG1
#define idac_hi_out__PA__CFG10 CYREG_UDB_PA3_CFG10
#define idac_hi_out__PA__CFG11 CYREG_UDB_PA3_CFG11
#define idac_hi_out__PA__CFG12 CYREG_UDB_PA3_CFG12
#define idac_hi_out__PA__CFG13 CYREG_UDB_PA3_CFG13
#define idac_hi_out__PA__CFG14 CYREG_UDB_PA3_CFG14
#define idac_hi_out__PA__CFG2 CYREG_UDB_PA3_CFG2
#define idac_hi_out__PA__CFG3 CYREG_UDB_PA3_CFG3
#define idac_hi_out__PA__CFG4 CYREG_UDB_PA3_CFG4
#define idac_hi_out__PA__CFG5 CYREG_UDB_PA3_CFG5
#define idac_hi_out__PA__CFG6 CYREG_UDB_PA3_CFG6
#define idac_hi_out__PA__CFG7 CYREG_UDB_PA3_CFG7
#define idac_hi_out__PA__CFG8 CYREG_UDB_PA3_CFG8
#define idac_hi_out__PA__CFG9 CYREG_UDB_PA3_CFG9
#define idac_hi_out__PC CYREG_PRT3_PC
#define idac_hi_out__PC2 CYREG_PRT3_PC2
#define idac_hi_out__PORT 3u
#define idac_hi_out__PS CYREG_PRT3_PS
#define idac_hi_out__SHIFT 0

/* idac_low_out */
#define idac_low_out__0__DM__MASK 0x38u
#define idac_low_out__0__DM__SHIFT 3
#define idac_low_out__0__DR CYREG_PRT3_DR
#define idac_low_out__0__HSIOM CYREG_HSIOM_PORT_SEL3
#define idac_low_out__0__HSIOM_MASK 0x000000F0u
#define idac_low_out__0__HSIOM_SHIFT 4u
#define idac_low_out__0__INTCFG CYREG_PRT3_INTCFG
#define idac_low_out__0__INTSTAT CYREG_PRT3_INTSTAT
#define idac_low_out__0__MASK 0x02u
#define idac_low_out__0__OUT_SEL CYREG_UDB_PA3_CFG10
#define idac_low_out__0__OUT_SEL_SHIFT 2u
#define idac_low_out__0__OUT_SEL_VAL 3u
#define idac_low_out__0__PA__CFG0 CYREG_UDB_PA3_CFG0
#define idac_low_out__0__PA__CFG1 CYREG_UDB_PA3_CFG1
#define idac_low_out__0__PA__CFG10 CYREG_UDB_PA3_CFG10
#define idac_low_out__0__PA__CFG11 CYREG_UDB_PA3_CFG11
#define idac_low_out__0__PA__CFG12 CYREG_UDB_PA3_CFG12
#define idac_low_out__0__PA__CFG13 CYREG_UDB_PA3_CFG13
#define idac_low_out__0__PA__CFG14 CYREG_UDB_PA3_CFG14
#define idac_low_out__0__PA__CFG2 CYREG_UDB_PA3_CFG2
#define idac_low_out__0__PA__CFG3 CYREG_UDB_PA3_CFG3
#define idac_low_out__0__PA__CFG4 CYREG_UDB_PA3_CFG4
#define idac_low_out__0__PA__CFG5 CYREG_UDB_PA3_CFG5
#define idac_low_out__0__PA__CFG6 CYREG_UDB_PA3_CFG6
#define idac_low_out__0__PA__CFG7 CYREG_UDB_PA3_CFG7
#define idac_low_out__0__PA__CFG8 CYREG_UDB_PA3_CFG8
#define idac_low_out__0__PA__CFG9 CYREG_UDB_PA3_CFG9
#define idac_low_out__0__PC CYREG_PRT3_PC
#define idac_low_out__0__PC2 CYREG_PRT3_PC2
#define idac_low_out__0__PORT 3u
#define idac_low_out__0__PS CYREG_PRT3_PS
#define idac_low_out__0__SHIFT 1
#define idac_low_out__DR CYREG_PRT3_DR
#define idac_low_out__INTCFG CYREG_PRT3_INTCFG
#define idac_low_out__INTSTAT CYREG_PRT3_INTSTAT
#define idac_low_out__MASK 0x02u
#define idac_low_out__PA__CFG0 CYREG_UDB_PA3_CFG0
#define idac_low_out__PA__CFG1 CYREG_UDB_PA3_CFG1
#define idac_low_out__PA__CFG10 CYREG_UDB_PA3_CFG10
#define idac_low_out__PA__CFG11 CYREG_UDB_PA3_CFG11
#define idac_low_out__PA__CFG12 CYREG_UDB_PA3_CFG12
#define idac_low_out__PA__CFG13 CYREG_UDB_PA3_CFG13
#define idac_low_out__PA__CFG14 CYREG_UDB_PA3_CFG14
#define idac_low_out__PA__CFG2 CYREG_UDB_PA3_CFG2
#define idac_low_out__PA__CFG3 CYREG_UDB_PA3_CFG3
#define idac_low_out__PA__CFG4 CYREG_UDB_PA3_CFG4
#define idac_low_out__PA__CFG5 CYREG_UDB_PA3_CFG5
#define idac_low_out__PA__CFG6 CYREG_UDB_PA3_CFG6
#define idac_low_out__PA__CFG7 CYREG_UDB_PA3_CFG7
#define idac_low_out__PA__CFG8 CYREG_UDB_PA3_CFG8
#define idac_low_out__PA__CFG9 CYREG_UDB_PA3_CFG9
#define idac_low_out__PC CYREG_PRT3_PC
#define idac_low_out__PC2 CYREG_PRT3_PC2
#define idac_low_out__PORT 3u
#define idac_low_out__PS CYREG_PRT3_PS
#define idac_low_out__SHIFT 1

/* Current_Sense */
#define Current_Sense__0__DM__MASK 0x7000u
#define Current_Sense__0__DM__SHIFT 12
#define Current_Sense__0__DR CYREG_PRT2_DR
#define Current_Sense__0__HSIOM CYREG_HSIOM_PORT_SEL2
#define Current_Sense__0__HSIOM_MASK 0x000F0000u
#define Current_Sense__0__HSIOM_SHIFT 16u
#define Current_Sense__0__INTCFG CYREG_PRT2_INTCFG
#define Current_Sense__0__INTSTAT CYREG_PRT2_INTSTAT
#define Current_Sense__0__MASK 0x10u
#define Current_Sense__0__PA__CFG0 CYREG_UDB_PA2_CFG0
#define Current_Sense__0__PA__CFG1 CYREG_UDB_PA2_CFG1
#define Current_Sense__0__PA__CFG10 CYREG_UDB_PA2_CFG10
#define Current_Sense__0__PA__CFG11 CYREG_UDB_PA2_CFG11
#define Current_Sense__0__PA__CFG12 CYREG_UDB_PA2_CFG12
#define Current_Sense__0__PA__CFG13 CYREG_UDB_PA2_CFG13
#define Current_Sense__0__PA__CFG14 CYREG_UDB_PA2_CFG14
#define Current_Sense__0__PA__CFG2 CYREG_UDB_PA2_CFG2
#define Current_Sense__0__PA__CFG3 CYREG_UDB_PA2_CFG3
#define Current_Sense__0__PA__CFG4 CYREG_UDB_PA2_CFG4
#define Current_Sense__0__PA__CFG5 CYREG_UDB_PA2_CFG5
#define Current_Sense__0__PA__CFG6 CYREG_UDB_PA2_CFG6
#define Current_Sense__0__PA__CFG7 CYREG_UDB_PA2_CFG7
#define Current_Sense__0__PA__CFG8 CYREG_UDB_PA2_CFG8
#define Current_Sense__0__PA__CFG9 CYREG_UDB_PA2_CFG9
#define Current_Sense__0__PC CYREG_PRT2_PC
#define Current_Sense__0__PC2 CYREG_PRT2_PC2
#define Current_Sense__0__PORT 2u
#define Current_Sense__0__PS CYREG_PRT2_PS
#define Current_Sense__0__SHIFT 4
#define Current_Sense__DR CYREG_PRT2_DR
#define Current_Sense__INTCFG CYREG_PRT2_INTCFG
#define Current_Sense__INTSTAT CYREG_PRT2_INTSTAT
#define Current_Sense__MASK 0x10u
#define Current_Sense__PA__CFG0 CYREG_UDB_PA2_CFG0
#define Current_Sense__PA__CFG1 CYREG_UDB_PA2_CFG1
#define Current_Sense__PA__CFG10 CYREG_UDB_PA2_CFG10
#define Current_Sense__PA__CFG11 CYREG_UDB_PA2_CFG11
#define Current_Sense__PA__CFG12 CYREG_UDB_PA2_CFG12
#define Current_Sense__PA__CFG13 CYREG_UDB_PA2_CFG13
#define Current_Sense__PA__CFG14 CYREG_UDB_PA2_CFG14
#define Current_Sense__PA__CFG2 CYREG_UDB_PA2_CFG2
#define Current_Sense__PA__CFG3 CYREG_UDB_PA2_CFG3
#define Current_Sense__PA__CFG4 CYREG_UDB_PA2_CFG4
#define Current_Sense__PA__CFG5 CYREG_UDB_PA2_CFG5
#define Current_Sense__PA__CFG6 CYREG_UDB_PA2_CFG6
#define Current_Sense__PA__CFG7 CYREG_UDB_PA2_CFG7
#define Current_Sense__PA__CFG8 CYREG_UDB_PA2_CFG8
#define Current_Sense__PA__CFG9 CYREG_UDB_PA2_CFG9
#define Current_Sense__PC CYREG_PRT2_PC
#define Current_Sense__PC2 CYREG_PRT2_PC2
#define Current_Sense__PORT 2u
#define Current_Sense__PS CYREG_PRT2_PS
#define Current_Sense__SHIFT 4

/* QuadButtonISR */
#define QuadButtonISR__INTC_CLR_EN_REG CYREG_CM0_ICER
#define QuadButtonISR__INTC_CLR_PD_REG CYREG_CM0_ICPR
#define QuadButtonISR__INTC_MASK 0x10u
#define QuadButtonISR__INTC_NUMBER 4u
#define QuadButtonISR__INTC_PRIOR_MASK 0xC0u
#define QuadButtonISR__INTC_PRIOR_NUM 3u
#define QuadButtonISR__INTC_PRIOR_REG CYREG_CM0_IPR1
#define QuadButtonISR__INTC_SET_EN_REG CYREG_CM0_ISER
#define QuadButtonISR__INTC_SET_PD_REG CYREG_CM0_ISPR

/* QuadratureISR */
#define QuadratureISR__INTC_CLR_EN_REG CYREG_CM0_ICER
#define QuadratureISR__INTC_CLR_PD_REG CYREG_CM0_ICPR
#define QuadratureISR__INTC_MASK 0x01u
#define QuadratureISR__INTC_NUMBER 0u
#define QuadratureISR__INTC_PRIOR_MASK 0xC0u
#define QuadratureISR__INTC_PRIOR_NUM 3u
#define QuadratureISR__INTC_PRIOR_REG CYREG_CM0_IPR0
#define QuadratureISR__INTC_SET_EN_REG CYREG_CM0_ISER
#define QuadratureISR__INTC_SET_PD_REG CYREG_CM0_ISPR

/* Voltage_Sense */
#define Voltage_Sense__0__DM__MASK 0xE00u
#define Voltage_Sense__0__DM__SHIFT 9
#define Voltage_Sense__0__DR CYREG_PRT2_DR
#define Voltage_Sense__0__HSIOM CYREG_HSIOM_PORT_SEL2
#define Voltage_Sense__0__HSIOM_MASK 0x0000F000u
#define Voltage_Sense__0__HSIOM_SHIFT 12u
#define Voltage_Sense__0__INTCFG CYREG_PRT2_INTCFG
#define Voltage_Sense__0__INTSTAT CYREG_PRT2_INTSTAT
#define Voltage_Sense__0__MASK 0x08u
#define Voltage_Sense__0__PA__CFG0 CYREG_UDB_PA2_CFG0
#define Voltage_Sense__0__PA__CFG1 CYREG_UDB_PA2_CFG1
#define Voltage_Sense__0__PA__CFG10 CYREG_UDB_PA2_CFG10
#define Voltage_Sense__0__PA__CFG11 CYREG_UDB_PA2_CFG11
#define Voltage_Sense__0__PA__CFG12 CYREG_UDB_PA2_CFG12
#define Voltage_Sense__0__PA__CFG13 CYREG_UDB_PA2_CFG13
#define Voltage_Sense__0__PA__CFG14 CYREG_UDB_PA2_CFG14
#define Voltage_Sense__0__PA__CFG2 CYREG_UDB_PA2_CFG2
#define Voltage_Sense__0__PA__CFG3 CYREG_UDB_PA2_CFG3
#define Voltage_Sense__0__PA__CFG4 CYREG_UDB_PA2_CFG4
#define Voltage_Sense__0__PA__CFG5 CYREG_UDB_PA2_CFG5
#define Voltage_Sense__0__PA__CFG6 CYREG_UDB_PA2_CFG6
#define Voltage_Sense__0__PA__CFG7 CYREG_UDB_PA2_CFG7
#define Voltage_Sense__0__PA__CFG8 CYREG_UDB_PA2_CFG8
#define Voltage_Sense__0__PA__CFG9 CYREG_UDB_PA2_CFG9
#define Voltage_Sense__0__PC CYREG_PRT2_PC
#define Voltage_Sense__0__PC2 CYREG_PRT2_PC2
#define Voltage_Sense__0__PORT 2u
#define Voltage_Sense__0__PS CYREG_PRT2_PS
#define Voltage_Sense__0__SHIFT 3
#define Voltage_Sense__DR CYREG_PRT2_DR
#define Voltage_Sense__INTCFG CYREG_PRT2_INTCFG
#define Voltage_Sense__INTSTAT CYREG_PRT2_INTSTAT
#define Voltage_Sense__MASK 0x08u
#define Voltage_Sense__PA__CFG0 CYREG_UDB_PA2_CFG0
#define Voltage_Sense__PA__CFG1 CYREG_UDB_PA2_CFG1
#define Voltage_Sense__PA__CFG10 CYREG_UDB_PA2_CFG10
#define Voltage_Sense__PA__CFG11 CYREG_UDB_PA2_CFG11
#define Voltage_Sense__PA__CFG12 CYREG_UDB_PA2_CFG12
#define Voltage_Sense__PA__CFG13 CYREG_UDB_PA2_CFG13
#define Voltage_Sense__PA__CFG14 CYREG_UDB_PA2_CFG14
#define Voltage_Sense__PA__CFG2 CYREG_UDB_PA2_CFG2
#define Voltage_Sense__PA__CFG3 CYREG_UDB_PA2_CFG3
#define Voltage_Sense__PA__CFG4 CYREG_UDB_PA2_CFG4
#define Voltage_Sense__PA__CFG5 CYREG_UDB_PA2_CFG5
#define Voltage_Sense__PA__CFG6 CYREG_UDB_PA2_CFG6
#define Voltage_Sense__PA__CFG7 CYREG_UDB_PA2_CFG7
#define Voltage_Sense__PA__CFG8 CYREG_UDB_PA2_CFG8
#define Voltage_Sense__PA__CFG9 CYREG_UDB_PA2_CFG9
#define Voltage_Sense__PC CYREG_PRT2_PC
#define Voltage_Sense__PC2 CYREG_PRT2_PC2
#define Voltage_Sense__PORT 2u
#define Voltage_Sense__PS CYREG_PRT2_PS
#define Voltage_Sense__SHIFT 3

/* Gate_Sense_Low */
#define Gate_Sense_Low__0__DM__MASK 0x1C0u
#define Gate_Sense_Low__0__DM__SHIFT 6
#define Gate_Sense_Low__0__DR CYREG_PRT2_DR
#define Gate_Sense_Low__0__HSIOM CYREG_HSIOM_PORT_SEL2
#define Gate_Sense_Low__0__HSIOM_MASK 0x00000F00u
#define Gate_Sense_Low__0__HSIOM_SHIFT 8u
#define Gate_Sense_Low__0__INTCFG CYREG_PRT2_INTCFG
#define Gate_Sense_Low__0__INTSTAT CYREG_PRT2_INTSTAT
#define Gate_Sense_Low__0__MASK 0x04u
#define Gate_Sense_Low__0__PA__CFG0 CYREG_UDB_PA2_CFG0
#define Gate_Sense_Low__0__PA__CFG1 CYREG_UDB_PA2_CFG1
#define Gate_Sense_Low__0__PA__CFG10 CYREG_UDB_PA2_CFG10
#define Gate_Sense_Low__0__PA__CFG11 CYREG_UDB_PA2_CFG11
#define Gate_Sense_Low__0__PA__CFG12 CYREG_UDB_PA2_CFG12
#define Gate_Sense_Low__0__PA__CFG13 CYREG_UDB_PA2_CFG13
#define Gate_Sense_Low__0__PA__CFG14 CYREG_UDB_PA2_CFG14
#define Gate_Sense_Low__0__PA__CFG2 CYREG_UDB_PA2_CFG2
#define Gate_Sense_Low__0__PA__CFG3 CYREG_UDB_PA2_CFG3
#define Gate_Sense_Low__0__PA__CFG4 CYREG_UDB_PA2_CFG4
#define Gate_Sense_Low__0__PA__CFG5 CYREG_UDB_PA2_CFG5
#define Gate_Sense_Low__0__PA__CFG6 CYREG_UDB_PA2_CFG6
#define Gate_Sense_Low__0__PA__CFG7 CYREG_UDB_PA2_CFG7
#define Gate_Sense_Low__0__PA__CFG8 CYREG_UDB_PA2_CFG8
#define Gate_Sense_Low__0__PA__CFG9 CYREG_UDB_PA2_CFG9
#define Gate_Sense_Low__0__PC CYREG_PRT2_PC
#define Gate_Sense_Low__0__PC2 CYREG_PRT2_PC2
#define Gate_Sense_Low__0__PORT 2u
#define Gate_Sense_Low__0__PS CYREG_PRT2_PS
#define Gate_Sense_Low__0__SHIFT 2
#define Gate_Sense_Low__DR CYREG_PRT2_DR
#define Gate_Sense_Low__INTCFG CYREG_PRT2_INTCFG
#define Gate_Sense_Low__INTSTAT CYREG_PRT2_INTSTAT
#define Gate_Sense_Low__MASK 0x04u
#define Gate_Sense_Low__PA__CFG0 CYREG_UDB_PA2_CFG0
#define Gate_Sense_Low__PA__CFG1 CYREG_UDB_PA2_CFG1
#define Gate_Sense_Low__PA__CFG10 CYREG_UDB_PA2_CFG10
#define Gate_Sense_Low__PA__CFG11 CYREG_UDB_PA2_CFG11
#define Gate_Sense_Low__PA__CFG12 CYREG_UDB_PA2_CFG12
#define Gate_Sense_Low__PA__CFG13 CYREG_UDB_PA2_CFG13
#define Gate_Sense_Low__PA__CFG14 CYREG_UDB_PA2_CFG14
#define Gate_Sense_Low__PA__CFG2 CYREG_UDB_PA2_CFG2
#define Gate_Sense_Low__PA__CFG3 CYREG_UDB_PA2_CFG3
#define Gate_Sense_Low__PA__CFG4 CYREG_UDB_PA2_CFG4
#define Gate_Sense_Low__PA__CFG5 CYREG_UDB_PA2_CFG5
#define Gate_Sense_Low__PA__CFG6 CYREG_UDB_PA2_CFG6
#define Gate_Sense_Low__PA__CFG7 CYREG_UDB_PA2_CFG7
#define Gate_Sense_Low__PA__CFG8 CYREG_UDB_PA2_CFG8
#define Gate_Sense_Low__PA__CFG9 CYREG_UDB_PA2_CFG9
#define Gate_Sense_Low__PC CYREG_PRT2_PC
#define Gate_Sense_Low__PC2 CYREG_PRT2_PC2
#define Gate_Sense_Low__PORT 2u
#define Gate_Sense_Low__PS CYREG_PRT2_PS
#define Gate_Sense_Low__SHIFT 2

/* Miscellaneous */
#define CYDEV_BCLK__HFCLK__HZ 24000000U
#define CYDEV_BCLK__HFCLK__KHZ 24000U
#define CYDEV_BCLK__HFCLK__MHZ 24U
#define CYDEV_BCLK__SYSCLK__HZ 24000000U
#define CYDEV_BCLK__SYSCLK__KHZ 24000U
#define CYDEV_BCLK__SYSCLK__MHZ 24U
#define CYDEV_CHIP_DIE_LEOPARD 1u
#define CYDEV_CHIP_DIE_PANTHER 4u
#define CYDEV_CHIP_DIE_PSOC4A 2u
#define CYDEV_CHIP_DIE_PSOC5LP 5u
#define CYDEV_CHIP_DIE_UNKNOWN 0u
#define CYDEV_CHIP_FAMILY_PSOC3 1u
#define CYDEV_CHIP_FAMILY_PSOC4 2u
#define CYDEV_CHIP_FAMILY_PSOC5 3u
#define CYDEV_CHIP_FAMILY_UNKNOWN 0u
#define CYDEV_CHIP_FAMILY_USED CYDEV_CHIP_FAMILY_PSOC4
#define CYDEV_CHIP_JTAG_ID 0x04A61193u
#define CYDEV_CHIP_MEMBER_3A 1u
#define CYDEV_CHIP_MEMBER_4A 2u
#define CYDEV_CHIP_MEMBER_4D 3u
#define CYDEV_CHIP_MEMBER_5A 4u
#define CYDEV_CHIP_MEMBER_5B 5u
#define CYDEV_CHIP_MEMBER_UNKNOWN 0u
#define CYDEV_CHIP_MEMBER_USED CYDEV_CHIP_MEMBER_4A
#define CYDEV_CHIP_DIE_EXPECT CYDEV_CHIP_MEMBER_USED
#define CYDEV_CHIP_DIE_ACTUAL CYDEV_CHIP_DIE_EXPECT
#define CYDEV_CHIP_REV_LEOPARD_ES1 0u
#define CYDEV_CHIP_REV_LEOPARD_ES2 1u
#define CYDEV_CHIP_REV_LEOPARD_ES3 3u
#define CYDEV_CHIP_REV_LEOPARD_PRODUCTION 3u
#define CYDEV_CHIP_REV_PANTHER_ES0 0u
#define CYDEV_CHIP_REV_PANTHER_ES1 1u
#define CYDEV_CHIP_REV_PANTHER_PRODUCTION 1u
#define CYDEV_CHIP_REV_PSOC4A_ES0 17u
#define CYDEV_CHIP_REV_PSOC4A_PRODUCTION 17u
#define CYDEV_CHIP_REV_PSOC5LP_ES0 0u
#define CYDEV_CHIP_REV_PSOC5LP_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_3A_ES1 0u
#define CYDEV_CHIP_REVISION_3A_ES2 1u
#define CYDEV_CHIP_REVISION_3A_ES3 3u
#define CYDEV_CHIP_REVISION_3A_PRODUCTION 3u
#define CYDEV_CHIP_REVISION_4A_ES0 17u
#define CYDEV_CHIP_REVISION_4A_PRODUCTION 17u
#define CYDEV_CHIP_REVISION_4D_ES0 0u
#define CYDEV_CHIP_REVISION_4D_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_5A_ES0 0u
#define CYDEV_CHIP_REVISION_5A_ES1 1u
#define CYDEV_CHIP_REVISION_5A_PRODUCTION 1u
#define CYDEV_CHIP_REVISION_5B_ES0 0u
#define CYDEV_CHIP_REVISION_5B_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_USED CYDEV_CHIP_REVISION_4A_PRODUCTION
#define CYDEV_CHIP_REV_EXPECT CYDEV_CHIP_REVISION_USED
#define CYDEV_CONFIG_READ_ACCELERATOR 1
#define CYDEV_CONFIG_UNUSED_IO_AllowButWarn 0
#define CYDEV_CONFIG_UNUSED_IO_AllowWithInfo 1
#define CYDEV_CONFIG_UNUSED_IO CYDEV_CONFIG_UNUSED_IO_AllowWithInfo
#define CYDEV_CONFIG_UNUSED_IO_Disallowed 2
#define CYDEV_CONFIGURATION_COMPRESSED 1
#define CYDEV_CONFIGURATION_MODE_COMPRESSED 0
#define CYDEV_CONFIGURATION_MODE CYDEV_CONFIGURATION_MODE_COMPRESSED
#define CYDEV_CONFIGURATION_MODE_DMA 2
#define CYDEV_CONFIGURATION_MODE_UNCOMPRESSED 1
#define CYDEV_DEBUG_PROTECT_KILL 4
#define CYDEV_DEBUG_PROTECT_OPEN 1
#define CYDEV_DEBUG_PROTECT CYDEV_DEBUG_PROTECT_OPEN
#define CYDEV_DEBUG_PROTECT_PROTECTED 2
#define CYDEV_DEBUGGING_DPS_Disable 3
#define CYDEV_DEBUGGING_DPS_SWD 2
#define CYDEV_DEBUGGING_DPS CYDEV_DEBUGGING_DPS_SWD
#define CYDEV_DEBUGGING_ENABLE 1
#define CYDEV_HEAP_SIZE 0x000
#define CYDEV_PROJ_TYPE 2
#define CYDEV_PROJ_TYPE_BOOTLOADER 1
#define CYDEV_PROJ_TYPE_LOADABLE 2
#define CYDEV_PROJ_TYPE_MULTIAPPBOOTLOADER 3
#define CYDEV_PROJ_TYPE_STANDARD 0
#define CYDEV_STACK_SIZE 0xFF
#define CYDEV_USE_BUNDLED_CMSIS 1
#define CYDEV_VARIABLE_VDDA 1
#define CYDEV_VDDA 5
#define CYDEV_VDDA_MV 5000
#define CYDEV_VDDD 5
#define CYDEV_VDDD_MV 5000
#define CYIPBLOCK_M0S8_CTBM_VERSION 0
#define CYIPBLOCK_m0s8cpuss_VERSION 0
#define CYIPBLOCK_m0s8csd_VERSION 0
#define CYIPBLOCK_m0s8gpio2_VERSION 0
#define CYIPBLOCK_m0s8hsiom4a_VERSION 0
#define CYIPBLOCK_m0s8lcd_VERSION 0
#define CYIPBLOCK_m0s8lpcomp_VERSION 0
#define CYIPBLOCK_m0s8pclk_VERSION 0
#define CYIPBLOCK_m0s8sar_VERSION 0
#define CYIPBLOCK_m0s8scb_VERSION 0
#define CYIPBLOCK_m0s8srssv2_VERSION 1
#define CYIPBLOCK_m0s8tcpwm_VERSION 0
#define CYIPBLOCK_m0s8udbif_VERSION 0
#define CYIPBLOCK_S8_GPIO_VERSION 2
#define CYDEV_BOOTLOADER_ENABLE 0

#endif /* INCLUDED_CYFITTER_H */
