/*******************************************************************************
 * File Name: project.h
 * PSoC Creator 3.0 Component Pack 7
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <IDAC.h>
#include <IDAC_Mux.h>
#include <Idac_High.h>
#include <Idac_High_aliases.h>
#include <Idac_Low.h>
#include <Idac_Low_aliases.h>
#include <Opamp_Pos_High.h>
#include <Opamp_Pos_High_aliases.h>
#include <Opamp_Pos_Low.h>
#include <Opamp_Pos_Low_aliases.h>
#include <Opamp_Mux.h>
#include <Opamp.h>
#include <Opamp_Out.h>
#include <Opamp_Out_aliases.h>
#include <opamp_neg.h>
#include <opamp_neg_aliases.h>
#include <Voltage_Sense.h>
#include <Voltage_Sense_aliases.h>
#include <Current_Sense.h>
#include <Current_Sense_aliases.h>
#include <ADC.h>
#include <DieTemp_1.h>
#include <UART.h>
#include <UART_SPI_UART.h>
#include <UART_PINS.h>
#include <UART_SPI_UART_PVT.h>
#include <UART_PVT.h>
#include <disp_ss.h>
#include <disp_ss_aliases.h>
#include <disp_mosi.h>
#include <disp_mosi_aliases.h>
#include <disp_sclk.h>
#include <disp_sclk_aliases.h>
#include <Clock_3.h>
#include <Display.h>
#include <Display_font.h>
#include <QuadButtonISR.h>
#include <QuadratureISR.h>
#include <Quadrature.h>
#include <Quadrature_aliases.h>
#include <Clock_2.h>
#include <disp_reset.h>
#include <disp_reset_aliases.h>
#include <QuadButton.h>
#include <QuadButton_aliases.h>
#include <Gate_Sense_Low.h>
#include <Gate_Sense_Low_aliases.h>
#include <UART_Clock.h>
#include <Opamp_In_Sense.h>
#include <Opamp_In_Sense_aliases.h>
#include <EEPROM.h>
#include <Backlight.h>
#include <Backlight_aliases.h>
#include <UART_ISR.h>
#include <ADC_intClock.h>
#include <ADC_IRQ.h>
#include <UART_rx.h>
#include <UART_rx_aliases.h>
#include <UART_tx.h>
#include <UART_tx_aliases.h>
#include <Display_SPI.h>
#include <Display_SPI_PVT.h>
#include <Display_SS_Reg.h>
#include <core_cm0_psoc4.h>
#include <core_cm0.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cyPm.h>
#include <cytypes.h>
#include <cypins.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

